/**
 * EDUCATION SATHI - BIHAR TOP COLLEGES & UNIVERSITIES MASTER DATASET
 * Complete 1 to 100 Colleges (Govt & Pvt MBBS, BDS Dental, BAMS Ayurveda, BHMS Homoeopathy,
 * IIT, NIT, IIM, State Engineering Colleges - GECs, Management, Law & Agriculture).
 */
const BIHAR_COLLEGES_DATA = [
  {
    "rank": 1,
    "name": "AIIMS Patna",
    "course": "MBBS",
    "type": "Central Govt",
    "seats": "125 Seats",
    "eligibility": "12th PCB + English (60% marks)",
    "entrance": "NEET-UG",
    "estFee": "₹5,856 total course fee",
    "city": "Patna",
    "category": "MBBS Medical",
    "counsellingBody": "MCC (100% AIQ)",
    "notes": "Premier Institute of National Importance (INI)",
    "id": "br-col-1",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 2,
    "name": "Patna Medical College (PMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "250 Seats",
    "eligibility": "12th PCB + English (50% UR, 40% Res)",
    "entrance": "NEET-UG",
    "estFee": "₹6,000 – ₹20,000 / year",
    "city": "Patna",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85% State) + MCC (15% AIQ)",
    "notes": "Oldest & apex medical college in Bihar, founded 1925",
    "id": "br-col-2",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 3,
    "name": "Indira Gandhi Institute of Medical Sciences (IGIMS)",
    "course": "MBBS",
    "type": "Autonomous Govt",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,00,000 / year (Govt Autonomous)",
    "city": "Patna",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC / MCC",
    "notes": "Super-specialty state apex medical institute",
    "id": "br-col-3",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 4,
    "name": "Nalanda Medical College & Hospital (NMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "200 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Patna",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Premier clinical hospital in Patna",
    "id": "br-col-4",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 5,
    "name": "Darbhanga Medical College & Hospital (DMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Darbhanga",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Historic North Bihar apex healthcare center",
    "id": "br-col-5",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 6,
    "name": "Jawaharlal Nehru Medical College (JLNMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Bhagalpur",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Eastern Bihar regional healthcare institute",
    "id": "br-col-6",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 7,
    "name": "Sri Krishna Medical College & Hospital (SKMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Muzaffarpur",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Premier North-West Bihar medical center",
    "id": "br-col-7",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 8,
    "name": "Anugrah Narayan Magadh Medical College (ANMMCH)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "120 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Gaya",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Magadh division referral hospital",
    "id": "br-col-8",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 9,
    "name": "Bhagwan Mahavir Institute of Medical Sciences (BMIMS)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "120 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Pawapuri, Nalanda",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Modern government medical college campus",
    "id": "br-col-9",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 10,
    "name": "Government Medical College (GMC), Bettiah",
    "course": "MBBS",
    "type": "Govt",
    "seats": "120 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Bettiah, West Champaran",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Champaran border healthcare lifeline",
    "id": "br-col-10",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 11,
    "name": "Jannayak Karpoori Thakur Medical College (JKTMC)",
    "course": "MBBS",
    "type": "Govt",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Madhepura",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Kosi division modern medical college",
    "id": "br-col-11",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 12,
    "name": "Government Medical College (GMC), Purnea",
    "course": "MBBS",
    "type": "Govt",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year",
    "city": "Purnea",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Seemanchal regional healthcare institute",
    "id": "br-col-12",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 13,
    "name": "ESIC Medical College & Hospital",
    "course": "MBBS",
    "type": "ESIC / Govt",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹24,000 / year (IP Quota / Govt)",
    "city": "Bihta, Patna",
    "category": "MBBS Medical",
    "counsellingBody": "MCC (All India ESIC Quota) + State UGMAC",
    "notes": "Central ESIC Ministry of Labour hospital",
    "id": "br-col-13",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 14,
    "name": "Katihar Medical College",
    "course": "MBBS",
    "type": "Private Minority",
    "seats": "200 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹11,05,000 / year (UGMAC Matrix)",
    "city": "Katihar",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (Open State + Muslim Minority)",
    "notes": "One of the most reputed private medical colleges in Bihar",
    "id": "br-col-14",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 15,
    "name": "Mata Gujri Memorial Medical College & Hospital",
    "course": "MBBS",
    "type": "Private Minority",
    "seats": "200 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹9,63,000 / year (UGMAC Matrix)",
    "city": "Kishanganj",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC (Open Merit + Sikh Minority)",
    "notes": "High patient flow & lowest private MBBS fee in Bihar",
    "id": "br-col-15",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 16,
    "name": "Narayan Medical College & Hospital (NMCH)",
    "course": "MBBS",
    "type": "Private",
    "seats": "250 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹11,15,000 / year (UGMAC Matrix)",
    "city": "Jamuhar, Sasaram",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Gopal Narayan Singh University campus",
    "id": "br-col-16",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 17,
    "name": "Lord Buddha Koshi Medical College & Hospital",
    "course": "MBBS",
    "type": "Private",
    "seats": "200 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹11,75,000 / year (UGMAC Matrix)",
    "city": "Saharsa",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Major private hospital in Kosi belt",
    "id": "br-col-17",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 18,
    "name": "Madhubani Medical College & Hospital",
    "course": "MBBS",
    "type": "Private Minority",
    "seats": "250 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹14,00,000 / year (UGMAC Matrix)",
    "city": "Madhubani",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State + Minority",
    "notes": "Modern multi-specialty healthcare facility",
    "id": "br-col-18",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 19,
    "name": "Netaji Subhas Medical College & Hospital (NSMCH)",
    "course": "MBBS",
    "type": "Private",
    "seats": "250 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹16,00,000 / year (UGMAC Matrix)",
    "city": "Bihta, Patna",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Rapidly growing medical campus near Patna capital",
    "id": "br-col-19",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 20,
    "name": "Shri Narayan Medical Institute & Hospital",
    "course": "MBBS",
    "type": "Private",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹10,50,000 / year (UGMAC Matrix)",
    "city": "Saharsa",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Modern diagnostic & tertiary clinical departments",
    "id": "br-col-20",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 21,
    "name": "Radha Devi Jageshwari Memorial (RDJM) Medical College",
    "course": "MBBS",
    "type": "Private",
    "seats": "200 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹13,35,000 / year (UGMAC Matrix)",
    "city": "Turki, Muzaffarpur",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Approved multi-specialty teaching hospital",
    "id": "br-col-21",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 22,
    "name": "Himalaya Medical College & Hospital",
    "course": "MBBS",
    "type": "Private",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,75,000 / year (UGMAC Matrix)",
    "city": "Paliganj, Patna",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Modern tertiary hospital in Patna district",
    "id": "br-col-22",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 23,
    "name": "Mahabodhi Medical College & Hospital",
    "course": "MBBS",
    "type": "Private",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹12,50,000 / year (UGMAC Regulated)",
    "city": "Sherghati, Gaya",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Approved teaching hospital in Gaya region",
    "id": "br-col-23",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 24,
    "name": "S.C.M.C. & S.P.N. Hospital Medical College",
    "course": "MBBS",
    "type": "Private",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹12,00,000 / year (UGMAC Regulated)",
    "city": "Khagaria",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Khagaria district healthcare infrastructure",
    "id": "br-col-24",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 25,
    "name": "Viraat Ramayan Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "seats": "150 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹13,00,000 / year (UGMAC Regulated)",
    "city": "East Champaran",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Comprehensive hospital with modern ICU",
    "id": "br-col-25",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 26,
    "name": "Buddha Hospital & Research Institute Medical College",
    "course": "MBBS",
    "type": "Private",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹12,50,000 / year (UGMAC Regulated)",
    "city": "Gaya",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Affiliated with prominent healthcare group",
    "id": "br-col-26",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 27,
    "name": "Shrinivas G Educational & Research Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹12,00,000 / year (UGMAC Regulated)",
    "city": "Saran (Chhapra)",
    "category": "MBBS Medical",
    "counsellingBody": "BCECEB UGMAC Open State Merit",
    "notes": "Newly established medical teaching facility",
    "id": "br-col-27",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 28,
    "name": "Patna Dental College & Hospital",
    "course": "BDS",
    "type": "Govt",
    "seats": "40 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹10,500 / year (Govt Dental)",
    "city": "Patna",
    "category": "BDS Dental",
    "counsellingBody": "BCECEB UGMAC (85%) + MCC (15%)",
    "notes": "Only government dental college in Bihar",
    "id": "br-col-28",
    "state": "Bihar",
    "duration": "5 Yr"
  },
  {
    "rank": 29,
    "name": "Buddha Institute of Dental Sciences & Hospital",
    "course": "BDS",
    "type": "Private",
    "seats": "100 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹3,30,000 / year (UGMAC Matrix)",
    "city": "Kankarbagh, Patna",
    "category": "BDS Dental",
    "counsellingBody": "BCECEB UGMAC Open Merit",
    "notes": "Leading dental surgery college with MDS specialization",
    "id": "br-col-29",
    "state": "Bihar",
    "duration": "5 Yr"
  },
  {
    "rank": 30,
    "name": "Mithila Minority Dental College & Hospital",
    "course": "BDS",
    "type": "Private Minority",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹3,00,000 / year (UGMAC Matrix)",
    "city": "Darbhanga",
    "category": "BDS Dental",
    "counsellingBody": "BCECEB UGMAC State Quota",
    "notes": "Reputed minority dental surgery institution",
    "id": "br-col-30",
    "state": "Bihar",
    "duration": "5 Yr"
  },
  {
    "rank": 31,
    "name": "Sarjug Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "seats": "40 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹3,15,000 / year (UGMAC Matrix)",
    "city": "Laheriasarai, Darbhanga",
    "category": "BDS Dental",
    "counsellingBody": "BCECEB UGMAC State Quota",
    "notes": "Well-established dental OPD & hospital",
    "id": "br-col-31",
    "state": "Bihar",
    "duration": "5 Yr"
  },
  {
    "rank": 32,
    "name": "Government Ayurvedic College & Hospital",
    "course": "BAMS",
    "type": "Govt",
    "seats": "125 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹18,000 / year (Govt Ayush)",
    "city": "Patna",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Apex Ayurveda college & research hospital in Bihar",
    "id": "br-col-32",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 33,
    "name": "Dayanand Ayurved Medical College & Hospital",
    "course": "BAMS",
    "type": "Private",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹2,25,000 / year",
    "city": "Siwan",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Affiliated Ayurvedic clinical training institution",
    "id": "br-col-33",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 34,
    "name": "Nitishwar Ayurved Medical College & Hospital",
    "course": "BAMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹2,10,000 / year",
    "city": "Muzaffarpur",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "NCISM recognized Ayurveda college",
    "id": "br-col-34",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 35,
    "name": "Shri Moti Singh Jageshwari Ayurved College & Hospital",
    "course": "BAMS",
    "type": "Private",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹2,20,000 / year",
    "city": "Chhapra / Saran",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Panchakarma & Ayurvedic therapy center",
    "id": "br-col-35",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 36,
    "name": "Shri Ravindranath Mukherji Ayurved College & Hospital",
    "course": "BAMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹2,00,000 / year",
    "city": "Motihari",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Champaran regional Ayurvedic college",
    "id": "br-col-36",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 37,
    "name": "Swami Raghvendracharya Tridandi Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹2,15,000 / year",
    "city": "Gaya",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Classical Ayurvedic studies & research",
    "id": "br-col-37",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 38,
    "name": "Ayurveda Mahavidyalaya, Ghughi Chowk",
    "course": "BAMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,95,000 / year",
    "city": "Gaya",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Teaching hospital with herbal dispensary",
    "id": "br-col-38",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 39,
    "name": "R.B.T.S. Government Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Govt",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹15,000 / year (Govt Homoeopathy)",
    "city": "Muzaffarpur",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Only state government homoeopathic medical college in Bihar",
    "id": "br-col-39",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 40,
    "name": "G.D. Memorial Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "60 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,80,000 / year",
    "city": "Kankarbagh, Patna",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Premier private homoeopathic teaching institute",
    "id": "br-col-40",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 41,
    "name": "B.N.M. Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,60,000 / year",
    "city": "Saharsa",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "NCH recognized homoeopathic hospital",
    "id": "br-col-41",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 42,
    "name": "K.N.H. Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,65,000 / year",
    "city": "Bhagalpur",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Prominent homoeopathic healthcare center in Bhagalpur",
    "id": "br-col-42",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 43,
    "name": "Magadh Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,50,000 / year",
    "city": "Biharsharif, Nalanda",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Hospital OPD with diagnostic laboratories",
    "id": "br-col-43",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 44,
    "name": "Dr. Rambalak Singh Gaya Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,55,000 / year",
    "city": "Gaya",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Clinical exposure in alternative healing",
    "id": "br-col-44",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 45,
    "name": "Dr. Yadubir Singh Sinha Homoeopathic Medical College & Hospital",
    "course": "BHMS",
    "type": "Private",
    "seats": "50 Seats",
    "eligibility": "12th PCB + English",
    "entrance": "NEET-UG",
    "estFee": "₹1,50,000 / year",
    "city": "Darbhanga",
    "category": "AYUSH (BAMS & BHMS)",
    "counsellingBody": "BCECEB UGMAC(Ayush)",
    "notes": "Mithilanchal homoeopathic education center",
    "id": "br-col-45",
    "state": "Bihar",
    "duration": "5.5 Yr"
  },
  {
    "rank": 46,
    "name": "IIT Patna (Indian Institute of Technology)",
    "course": "B.Tech, M.Tech, MBA",
    "type": "Central Govt",
    "seats": "750+ B.Tech Seats",
    "eligibility": "10+2 with PCM (75% aggregate)",
    "entrance": "JEE Advanced / GATE / CAT",
    "estFee": "₹2,20,000 / year (Govt Subsidized)",
    "city": "Bihta, Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "JoSAA / CSAB",
    "notes": "Institute of National Importance (NIRF Top Ranker)",
    "id": "br-col-46",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 47,
    "name": "NIT Patna (National Institute of Technology)",
    "course": "B.Tech, M.Tech, MCA, MBA",
    "type": "Central Govt",
    "seats": "900+ B.Tech Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main / GATE / NIMCET",
    "estFee": "₹1,45,000 / year",
    "city": "Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "JoSAA / CSAB (50% Home State Quota)",
    "notes": "Historic technical institute, established 1886",
    "id": "br-col-47",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 48,
    "name": "IIM Bodh Gaya (Indian Institute of Management)",
    "course": "MBA, IPM, MBA-DBM, MBA-HHM",
    "type": "Central Govt",
    "seats": "300+ MBA Seats",
    "eligibility": "Graduation (50% UR, 45% Res) / 10+2 for IPM",
    "entrance": "CAT / JIPMAT",
    "estFee": "₹8,50,000 / year",
    "city": "Bodh Gaya",
    "category": "Management & Law",
    "counsellingBody": "CAP / IIM Direct",
    "notes": "Premier National Management Institution of India",
    "id": "br-col-48",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 49,
    "name": "IIIT Bhagalpur (Indian Institute of Information Technology)",
    "course": "B.Tech (CSE, ECE, ME, Mechatronics)",
    "type": "Central Govt (PPP)",
    "seats": "350+ Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main",
    "estFee": "₹2,10,000 / year",
    "city": "Bhagalpur",
    "category": "Engineering & Tech",
    "counsellingBody": "JoSAA / CSAB",
    "notes": "National importance IT & electronics institute",
    "id": "br-col-49",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 50,
    "name": "Chandragupt Institute of Management Patna (CIMP)",
    "course": "PGDM (MBA Equivalent)",
    "type": "Govt Supported Autonomous",
    "seats": "120 Seats",
    "eligibility": "Graduation (50%)",
    "entrance": "CAT / XAT / CMAT",
    "estFee": "₹3,90,000 / year",
    "city": "Mithapur, Patna",
    "category": "Management & Law",
    "counsellingBody": "CIMP State Merit",
    "notes": "AICTE approved, NBA accredited, AIU MBA equivalency",
    "id": "br-col-50",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 51,
    "name": "Chanakya National Law University (CNLU)",
    "course": "B.A. LL.B (Hons), BBA LL.B, LL.M",
    "type": "State National Law University",
    "seats": "140 Seats",
    "eligibility": "10+2 (45% UR, 40% SC/ST)",
    "entrance": "CLAT UG / PG",
    "estFee": "₹2,40,000 / year",
    "city": "Patna",
    "category": "Management & Law",
    "counsellingBody": "Consortium of NLUs",
    "notes": "Top National Law University in Bihar",
    "id": "br-col-51",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 52,
    "name": "BIT Patna (Birla Institute of Technology Extension)",
    "course": "B.Tech, B.Arch, M.Tech, MBA",
    "type": "Private / Deemed Extension",
    "seats": "360 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main",
    "estFee": "₹3,10,000 / year",
    "city": "Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "CSAB / Institutional",
    "notes": "High placement record in tech & IT sector",
    "id": "br-col-52",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 53,
    "name": "Muzaffarpur Institute of Technology (MIT)",
    "course": "B.Tech, M.Tech, B.Pharm",
    "type": "Govt",
    "seats": "350+ Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year (Govt Engineering)",
    "city": "Muzaffarpur",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Oldest state engineering college in Bihar, founded 1954",
    "id": "br-col-53",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 54,
    "name": "Bhagalpur College of Engineering (BCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300+ Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Bhagalpur",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Prominent state government engineering institute",
    "id": "br-col-54",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 55,
    "name": "Nalanda College of Engineering (NCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300+ Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Chandi, Nalanda",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Modern state technical college campus",
    "id": "br-col-55",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 56,
    "name": "Lok Nayak Jai Prakash Institute of Technology (LNJPIT)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Chhapra",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Saran division state engineering college",
    "id": "br-col-56",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 57,
    "name": "Darbhanga College of Engineering (DCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Darbhanga",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Key government engineering campus in Mithila",
    "id": "br-col-57",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 58,
    "name": "Gaya College of Engineering (GCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Gaya",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "TEQIP assisted state engineering college",
    "id": "br-col-58",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 59,
    "name": "Bakhtiyarpur College of Engineering (BCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Bakhtiyarpur, Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Modern campus with robotics and AI labs",
    "id": "br-col-59",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 60,
    "name": "Motihari College of Engineering (MCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Motihari",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "East Champaran premier state technical college",
    "id": "br-col-60",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 61,
    "name": "Purnea College of Engineering (PCE)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Purnea",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Seemanchal regional engineering institute",
    "id": "br-col-61",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 62,
    "name": "Supaul College of Engineering",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Supaul",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Kosi belt state engineering college",
    "id": "br-col-62",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 63,
    "name": "Sitamarhi Institute of Technology (SIT)",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Sitamarhi",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Approved state government engineering institute",
    "id": "br-col-63",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 64,
    "name": "Sershah Engineering College",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Sasaram, Rohtas",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Rohtas district state technical college",
    "id": "br-col-64",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 65,
    "name": "Government Engineering College (GEC), Vaishali",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Vaishali",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Modern state technical college",
    "id": "br-col-65",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 66,
    "name": "Government Engineering College (GEC), Nawada",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Nawada",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "State government engineering institute",
    "id": "br-col-66",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 67,
    "name": "Government Engineering College (GEC), Jamui",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Jamui",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "District government engineering campus",
    "id": "br-col-67",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 68,
    "name": "Government Engineering College (GEC), Banka",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Banka",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "State technical education department institute",
    "id": "br-col-68",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 69,
    "name": "Government Engineering College (GEC), Kaimur",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Kaimur",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Government technical college",
    "id": "br-col-69",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 70,
    "name": "Government Engineering College, West Champaran",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "West Champaran",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Established under Saat Nischay technical roadmap",
    "id": "br-col-70",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 71,
    "name": "Government Engineering College (GEC), Patna",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "New state capital technical engineering college",
    "id": "br-col-71",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 72,
    "name": "Government Engineering College (GEC), Araria",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Araria",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "District technical institution",
    "id": "br-col-72",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 73,
    "name": "Government Engineering College (GEC), Aurangabad",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Aurangabad",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "State engineering college",
    "id": "br-col-73",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 74,
    "name": "Government Engineering College (GEC), Jehanabad",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Jehanabad",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Modern state technical college",
    "id": "br-col-74",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 75,
    "name": "Government Engineering College (GEC), Madhubani",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Madhubani",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "District engineering campus",
    "id": "br-col-75",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 76,
    "name": "Dr. Rajendra Prasad Central Agricultural University (RPCAU)",
    "course": "B.Sc Agriculture, B.Tech Biotech, MBA Agribusiness",
    "type": "Central Govt University",
    "seats": "450+ Seats",
    "eligibility": "10+2 with PCB/PCM",
    "entrance": "CUET / ICAR AIEEA",
    "estFee": "₹35,000 / year",
    "city": "Pusa, Samastipur",
    "category": "Management & Law",
    "counsellingBody": "ICAR / Central University",
    "notes": "Historic Central Agricultural University of India",
    "id": "br-col-76",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 77,
    "name": "Bihar Agricultural University (BAU)",
    "course": "B.Sc (Hons) Agriculture, M.Sc Ag",
    "type": "State Govt",
    "seats": "300+ Seats",
    "eligibility": "10+2 with PCB/PCM",
    "entrance": "BCECE / ICAR",
    "estFee": "₹18,000 / year",
    "city": "Sabour, Bhagalpur",
    "category": "Management & Law",
    "counsellingBody": "BCECEB Agriculture Counselling",
    "notes": "Apex state agricultural university",
    "id": "br-col-77",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 78,
    "name": "LN Mishra Institute of Economic Development & Social Change",
    "course": "MBA, MCA, BBA, BCA",
    "type": "Govt Autonomous",
    "seats": "240 Seats",
    "eligibility": "Graduation (50%)",
    "entrance": "MAT / CMAT / Institutional",
    "estFee": "₹1,60,000 / year",
    "city": "Patna",
    "category": "Management & Law",
    "counsellingBody": "State Merit",
    "notes": "Premier management & computer application institute",
    "id": "br-col-78",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 79,
    "name": "Bihar College of Pharmacy",
    "course": "B.Pharm, D.Pharm",
    "type": "Private",
    "seats": "100 Seats",
    "eligibility": "10+2 with PCB/PCM",
    "entrance": "BCECE / Merit",
    "estFee": "₹1,20,000 / year",
    "city": "Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "PCI / AKU Affiliation",
    "notes": "Pioneering pharmacy institute in Bihar",
    "id": "br-col-79",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 80,
    "name": "Government Pharmacy Institute",
    "course": "B.Pharm, D.Pharm",
    "type": "Govt",
    "seats": "60 Seats",
    "eligibility": "10+2 with PCB/PCM",
    "entrance": "BCECE",
    "estFee": "₹12,000 / year",
    "city": "Agamkuan, Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB",
    "notes": "Premier government pharmacy institute",
    "id": "br-col-80",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 81,
    "name": "Patna Law College",
    "course": "LL.B (3 Years)",
    "type": "Govt",
    "seats": "120 Seats",
    "eligibility": "Graduation (45% UR, 40% SC/ST)",
    "entrance": "Patna University Entrance Test",
    "estFee": "₹8,000 / year",
    "city": "Patna",
    "category": "Management & Law",
    "counsellingBody": "Patna University",
    "notes": "Historic law faculty, produced Supreme Court judges & leaders",
    "id": "br-col-81",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 82,
    "name": "Patna Women's College (Autonomous)",
    "course": "BBA, BCA, B.Com (Hons), B.Sc",
    "type": "Autonomous / Private",
    "seats": "1,200+ Seats",
    "eligibility": "10+2 Merit",
    "entrance": "PWC Entrance Exam (PUCET)",
    "estFee": "₹45,000 – ₹70,000 / year",
    "city": "Bailey Road, Patna",
    "category": "Management & Law",
    "counsellingBody": "PWC Direct Merit",
    "notes": "NAAC 'A+' Grade premier women's college",
    "id": "br-col-82",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 83,
    "name": "St. Xavier's College of Management & Technology",
    "course": "BBA, BCA, B.Com, BMC",
    "type": "Private",
    "seats": "360 Seats",
    "eligibility": "10+2 (50%)",
    "entrance": "College Entrance Test & Interview",
    "estFee": "₹85,000 / year",
    "city": "Digha, Patna",
    "category": "Management & Law",
    "counsellingBody": "Jesuit Educational Council",
    "notes": "Top-tier discipline & corporate placement track record",
    "id": "br-col-83",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 84,
    "name": "CIMAGE Professional College",
    "course": "BBA, BCA, B.Com, MCA",
    "type": "Private",
    "seats": "480 Seats",
    "eligibility": "10+2 Merit",
    "entrance": "CIMAGE Entrance Test",
    "estFee": "₹75,000 / year",
    "city": "Boring Road, Patna",
    "category": "Management & Law",
    "counsellingBody": "AKU / PPU Affiliation",
    "notes": "Highest BCA/BBA campus placements in Bihar",
    "id": "br-col-84",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 85,
    "name": "College of Commerce, Arts & Science",
    "course": "BBA, BCA, B.Com, B.Sc, M.Sc",
    "type": "Govt Constituent",
    "seats": "2,000+ Seats",
    "eligibility": "10+2 Merit",
    "entrance": "Patliputra University Portal",
    "estFee": "₹12,000 / year",
    "city": "Kankarbagh, Patna",
    "category": "Management & Law",
    "counsellingBody": "PPU Centralised Admission",
    "notes": "NAAC 'A' Grade university constituent college",
    "id": "br-col-85",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 86,
    "name": "Patna Science College",
    "course": "B.Sc (Hons) Physics, Chemistry, Maths, Bio",
    "type": "Govt Constituent",
    "seats": "600+ Seats",
    "eligibility": "10+2 Science (55%)",
    "entrance": "PUCET",
    "estFee": "₹8,000 / year",
    "city": "Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "Patna University",
    "notes": "Legendary science college of Eastern India",
    "id": "br-col-86",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 87,
    "name": "A.N. College, Patna",
    "course": "BCA, BBA, B.Sc, Environmental Sciences",
    "type": "Govt Constituent",
    "seats": "2,500+ Seats",
    "eligibility": "10+2 Merit",
    "entrance": "PPU Portal",
    "estFee": "₹10,000 – ₹25,000 / year",
    "city": "Boring Road, Patna",
    "category": "Management & Law",
    "counsellingBody": "Patliputra University",
    "notes": "College with Potential for Excellence (UGC CPE)",
    "id": "br-col-87",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 88,
    "name": "International School of Management (ISM Patna)",
    "course": "BBA, BCA, B.Com, PGDM",
    "type": "Private",
    "seats": "180 Seats",
    "eligibility": "10+2 (50%) / Graduation",
    "entrance": "CAT / MAT / ISM Test",
    "estFee": "₹1,40,000 / year",
    "city": "Khagaul, Patna",
    "category": "Management & Law",
    "counsellingBody": "ISM Admission Cell",
    "notes": "Dedicated corporate business school",
    "id": "br-col-88",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 89,
    "name": "Netaji Subhas Institute of Technology (NSIT)",
    "course": "B.Tech, Polytechnic",
    "type": "Private",
    "seats": "420 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main / BCECEB",
    "estFee": "₹95,000 / year",
    "city": "Bihta, Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "AKU Affiliation",
    "notes": "Approved AICTE private engineering institute",
    "id": "br-col-89",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 90,
    "name": "Buddha Institute of Technology",
    "course": "B.Tech, Polytechnic Diploma",
    "type": "Private",
    "seats": "360 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main / Institute",
    "estFee": "₹85,000 / year",
    "city": "Gaya",
    "category": "Engineering & Tech",
    "counsellingBody": "AKU Affiliated",
    "notes": "Leading private engineering institute in Magadh",
    "id": "br-col-90",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 91,
    "name": "Central University of South Bihar (CUSB)",
    "course": "Integrated B.A. LL.B, B.Sc. B.Ed, M.Sc, M.Tech",
    "type": "Central Govt",
    "seats": "800+ Seats",
    "eligibility": "10+2 / Graduation",
    "entrance": "CUET-UG / CUET-PG",
    "estFee": "₹25,000 / year",
    "city": "Panchanpur, Gaya",
    "category": "Management & Law",
    "counsellingBody": "CUET / NTA",
    "notes": "NAAC 'A++' Grade Central University",
    "id": "br-col-91",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 92,
    "name": "Nalanda Open University",
    "course": "BCA, B.LIS, BBA, MA, M.Sc",
    "type": "State Govt Open University",
    "seats": "Open Enrolment",
    "eligibility": "10+2 / Graduation",
    "entrance": "Direct Merit",
    "estFee": "₹6,000 – ₹15,000 / year",
    "city": "Patna",
    "category": "Management & Law",
    "counsellingBody": "State Open Admission",
    "notes": "Only open university in Bihar for distance education",
    "id": "br-col-92",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 93,
    "name": "College of Horticulture, Noorsarai",
    "course": "B.Sc (Hons) Horticulture",
    "type": "Govt",
    "seats": "60 Seats",
    "eligibility": "10+2 with PCB/PCM",
    "entrance": "BCECE",
    "estFee": "₹18,000 / year",
    "city": "Noorsarai, Nalanda",
    "category": "Management & Law",
    "counsellingBody": "BCECEB",
    "notes": "Constituent college of Bihar Agricultural University",
    "id": "br-col-93",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 94,
    "name": "College of Fisheries",
    "course": "B.F.Sc (Bachelor of Fisheries Science)",
    "type": "Govt",
    "seats": "40 Seats",
    "eligibility": "10+2 with PCB",
    "entrance": "BCECE",
    "estFee": "₹18,000 / year",
    "city": "Kishanganj",
    "category": "Management & Law",
    "counsellingBody": "BCECEB",
    "notes": "Specialized fisheries science research center",
    "id": "br-col-94",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 95,
    "name": "College of Forestry, RPCAU",
    "course": "B.Sc (Hons) Forestry",
    "type": "Central Govt",
    "seats": "50 Seats",
    "eligibility": "10+2 with PCB",
    "entrance": "CUET / ICAR",
    "estFee": "₹35,000 / year",
    "city": "Pusa, Samastipur",
    "category": "Management & Law",
    "counsellingBody": "ICAR",
    "notes": "Central forestry and environmental sciences faculty",
    "id": "br-col-95",
    "state": "Bihar",
    "duration": "2-3 Yr"
  },
  {
    "rank": 96,
    "name": "Government Polytechnic, Patna-7",
    "course": "Diploma Engineering (Civil, Mech, Electrical, CSE)",
    "type": "Govt",
    "seats": "360 Seats",
    "eligibility": "10th Pass (35%)",
    "entrance": "DCECE (PE)",
    "estFee": "₹2,500 / year",
    "city": "Gulzarbagh, Patna",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB DCECE",
    "notes": "Top-ranked government polytechnic institute in Bihar",
    "id": "br-col-96",
    "state": "Bihar",
    "duration": "3 Yr"
  },
  {
    "rank": 97,
    "name": "Government Polytechnic, Muzaffarpur",
    "course": "Diploma Engineering",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10th Pass",
    "entrance": "DCECE (PE)",
    "estFee": "₹2,500 / year",
    "city": "Muzaffarpur",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB DCECE",
    "notes": "Key technical polytechnic institute in North Bihar",
    "id": "br-col-97",
    "state": "Bihar",
    "duration": "3 Yr"
  },
  {
    "rank": 98,
    "name": "Government Polytechnic, Gaya",
    "course": "Diploma Engineering",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10th Pass",
    "entrance": "DCECE (PE)",
    "estFee": "₹2,500 / year",
    "city": "Gaya",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB DCECE",
    "notes": "Oldest polytechnic institute in South Bihar",
    "id": "br-col-98",
    "state": "Bihar",
    "duration": "3 Yr"
  },
  {
    "rank": 99,
    "name": "Government Engineering College, Munger",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Munger",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Modern government engineering college in Munger",
    "id": "br-col-99",
    "state": "Bihar",
    "duration": "4 Yr"
  },
  {
    "rank": 100,
    "name": "Government Engineering College, Buxar",
    "course": "B.Tech",
    "type": "Govt",
    "seats": "300 Seats",
    "eligibility": "10+2 with PCM",
    "entrance": "JEE Main (via UGEAC)",
    "estFee": "₹10,500 / year",
    "city": "Buxar",
    "category": "Engineering & Tech",
    "counsellingBody": "BCECEB UGEAC",
    "notes": "Approved state government technical institute",
    "id": "br-col-100",
    "state": "Bihar",
    "duration": "4 Yr"
  }
];
