/**
 * EDUCATION SATHI - Master Dataset
 * 28 States + 8 Union Territories (36 Total), Dedicated Medical Boxes (MBBS, BHMS, BAMS, BUMS, MD/MS),
 * 25+ Career Categories, 500+ Courses, Top Universities & Colleges, Scholarships, and Counselling Authorities.
 */

const EDUCATION_DATA = {
  // =========================================================================
  // 1. ALL 28 INDIAN STATES + 8 UNION TERRITORIES (36 DESTINATIONS)
  // =========================================================================
  destinations: [
    // --- 28 STATES ---
    {
      id: "madhya-pradesh",
      name: "Madhya Pradesh",
      type: "State",
      code: "MP",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
      govtColleges: 85,
      pvtColleges: 240,
      universities: 42,
      medicalColleges: 26,
      topColleges: ["GMC Bhopal", "MGM Indore", "AIIMS Bhopal", "SGSITS Indore", "IIT Indore", "IIM Indore"],
      popularCourses: ["MBBS", "B.Tech CSE", "BAMS", "MBA", "B.Pharm", "B.Sc Agriculture"],
      counsellingBody: "MP DME (Medical) / MP DTE (Engineering) / MP Higher Education",
      highlights: "Home to Education Sathi HQ. Hub of premier medical institutions, AIIMS Bhopal, and 100% MMVY scholarship support."
    },
    {
      id: "uttar-pradesh",
      name: "Uttar Pradesh",
      type: "State",
      code: "UP",
      image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
      cities: ["Lucknow", "Noida", "Varanasi", "Kanpur", "Meerut", "Prayagraj"],
      govtColleges: 160,
      pvtColleges: 480,
      universities: 75,
      medicalColleges: 68,
      topColleges: ["KGMU Lucknow", "BHU Varanasi", "SGPGIMS", "IIT Kanpur", "Sharda University", "AMU Aligarh"],
      popularCourses: ["MBBS", "MD/MS", "B.Tech AI", "LLB", "B.Ed", "BAMS"],
      counsellingBody: "UP DGME (Open State for Private Medical Colleges) / AKTU",
      highlights: "Largest education hub in North India. Open state policy for private medical colleges with direct MCC & UP NEET counselling."
    },
    {
      id: "maharashtra",
      name: "Maharashtra",
      type: "State",
      code: "MH",
      image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
      cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
      govtColleges: 130,
      pvtColleges: 520,
      universities: 65,
      medicalColleges: 62,
      topColleges: ["Grant Medical College", "DY Patil Pune", "IIT Bombay", "COEP Pune", "TISS Mumbai", "KEM Hospital"],
      popularCourses: ["MBBS", "B.Tech", "MBA Finance", "B.Sc Nursing", "B.Des UI/UX", "B.Pharm"],
      counsellingBody: "State CET Cell Maharashtra / DMER",
      highlights: "Financial & Tech capital with world-renowned medical teaching hospitals and top Deemed Universities."
    },
    {
      id: "karnataka",
      name: "Karnataka",
      type: "State",
      code: "KA",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Bengaluru", "Mysuru", "Mangalore", "Manipal", "Belagavi"],
      govtColleges: 110,
      pvtColleges: 460,
      universities: 58,
      medicalColleges: 70,
      topColleges: ["KMC Manipal", "BMCRI Bangalore", "St. John's", "IISc Bangalore", "JSS Mysore", "MS Ramaiah"],
      popularCourses: ["MBBS", "B.Tech CSE/AI", "BDS", "Pharm.D", "MBA", "Physiotherapy"],
      counsellingBody: "Karnataka Examinations Authority (KEA)",
      highlights: "Silicon Valley of India with the highest density of top-ranked Medical and Engineering colleges."
    },
    {
      id: "rajasthan",
      name: "Rajasthan",
      type: "State",
      code: "RJ",
      image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
      cities: ["Jaipur", "Kota", "Jodhpur", "Udaipur", "Ajmer"],
      govtColleges: 95,
      pvtColleges: 310,
      universities: 52,
      medicalColleges: 34,
      topColleges: ["SMS Jaipur", "AIIMS Jodhpur", "BITS Pilani", "MNIT Jaipur", "Geetanjali Udaipur"],
      popularCourses: ["MBBS", "B.Tech", "BAMS", "B.Sc Nursing", "Hotel Management"],
      counsellingBody: "Rajasthan NEET UG Medical Board / REAP",
      highlights: "India's coaching and medical foundation capital with prominent government medical colleges."
    },
    {
      id: "delhi",
      name: "Delhi (NCR)",
      type: "Union Territory",
      code: "DL",
      image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
      cities: ["New Delhi", "North Delhi", "South Delhi"],
      govtColleges: 45,
      pvtColleges: 90,
      universities: 30,
      medicalColleges: 10,
      topColleges: ["AIIMS New Delhi", "MAMC", "VMMC Safdarjung", "IIT Delhi", "Delhi University (DU)", "DTU"],
      popularCourses: ["MBBS (AIQ)", "B.Tech", "BA Hons", "LLB (CLAT)", "MBA (FMS/DSE)"],
      counsellingBody: "MCC (AIIMS/VMMC) / IPU CET / DU CSAS",
      highlights: "National capital territory with #1 NIRF ranked AIIMS New Delhi and premier central universities."
    },
    {
      id: "tamil-nadu",
      name: "Tamil Nadu",
      type: "State",
      code: "TN",
      image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
      cities: ["Chennai", "Coimbatore", "Vellore", "Madurai", "Tiruchirappalli"],
      govtColleges: 140,
      pvtColleges: 580,
      universities: 60,
      medicalColleges: 72,
      topColleges: ["CMC Vellore", "Madras Medical College (MMC)", "IIT Madras", "SRM Chennai", "PSG Tech"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Nursing", "Pharm.D", "Allied Health", "BPT"],
      counsellingBody: "TN Health Selection Committee / TNEA",
      highlights: "Medical healthcare capital of South Asia with world-class hospital training and high clinical exposure."
    },
    {
      id: "gujarat",
      name: "Gujarat",
      type: "State",
      code: "GJ",
      image: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800&auto=format&fit=crop&q=80",
      cities: ["Ahmedabad", "Vadodara", "Surat", "Rajkot", "Gandhinagar"],
      govtColleges: 70,
      pvtColleges: 260,
      universities: 40,
      medicalColleges: 38,
      topColleges: ["BJ Medical College", "AIIMS Rajkot", "IIM Ahmedabad", "SVNIT Surat", "Parul University"],
      popularCourses: ["MBBS", "B.Tech", "BBA", "B.Pharm", "Diploma Engg"],
      counsellingBody: "ACPUGMEC Gujarat / ACPC",
      highlights: "Fastest-growing educational infrastructure with state-of-the-art GMERS and private medical campuses."
    },
    {
      id: "bihar",
      name: "Bihar",
      type: "State",
      code: "BR",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"],
      govtColleges: 80,
      pvtColleges: 180,
      universities: 35,
      medicalColleges: 20,
      topColleges: ["PMCH Patna", "AIIMS Patna", "IGIMS", "IIT Patna", "NIT Patna"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Nursing", "B.Ed", "Polytechnic"],
      counsellingBody: "BCECEB (UGMAC)",
      highlights: "Historic seat of learning with PMCH's world-record 5400-bed hospital expansion."
    },
    {
      id: "telangana",
      name: "Telangana",
      type: "State",
      code: "TS",
      image: "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=800&auto=format&fit=crop&q=80",
      cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar"],
      govtColleges: 75,
      pvtColleges: 340,
      universities: 32,
      medicalColleges: 46,
      topColleges: ["Osmania Medical College", "Gandhi Medical College", "AIIMS Bibinagar", "IIT Hyderabad", "ISB"],
      popularCourses: ["MBBS", "B.Tech AI/ML", "B.Pharm", "BDS", "MCA"],
      counsellingBody: "KNRUHS Telangana / TS EAMCET",
      highlights: "Major pharma, biotech, and IT destination with extensive modern hospital infrastructure."
    },
    {
      id: "andhra-pradesh",
      name: "Andhra Pradesh",
      type: "State",
      code: "AP",
      image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
      cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati"],
      govtColleges: 70,
      pvtColleges: 320,
      universities: 30,
      medicalColleges: 36,
      topColleges: ["Andhra Medical College", "AIIMS Mangalagiri", "SVIMS Tirupati", "IIT Tirupati"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Agriculture", "B.Pharm", "Physiotherapy"],
      counsellingBody: "YSRUHS AP / AP EAPCET",
      highlights: "Prominent medical hubs with top NIRF-ranked institutions and specialized clinical centres."
    },
    {
      id: "kerala",
      name: "Kerala",
      type: "State",
      code: "KL",
      image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
      cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur"],
      govtColleges: 65,
      pvtColleges: 210,
      universities: 26,
      medicalColleges: 33,
      topColleges: ["GMC Trivandrum", "Amrita School of Medicine (Kochi)", "Calicut Medical College", "NIT Calicut"],
      popularCourses: ["MBBS", "Ayurveda (BAMS)", "B.Sc Nursing", "Allied Health", "B.Tech"],
      counsellingBody: "CEE Kerala (KEAM)",
      highlights: "100% literacy state, world capital for authentic Ayurveda and premier medical care."
    },
    {
      id: "west-bengal",
      name: "West Bengal",
      type: "State",
      code: "WB",
      image: "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&auto=format&fit=crop&q=80",
      cities: ["Kolkata", "Siliguri", "Durgapur", "Kalyani", "Asansol"],
      govtColleges: 90,
      pvtColleges: 270,
      universities: 44,
      medicalColleges: 34,
      topColleges: ["Medical College Kolkata (Oldest in Asia)", "IPGMER", "AIIMS Kalyani", "IIT Kharagpur", "Jadavpur University"],
      popularCourses: ["MBBS", "B.Tech", "BHMS", "B.Sc Biotechnology", "B.Ed"],
      counsellingBody: "WBJEEB / WBMCC",
      highlights: "Pioneer of medical education in India with Asia's oldest medical college established in 1835."
    },
    {
      id: "chhattisgarh",
      name: "Chhattisgarh",
      type: "State",
      code: "CG",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Raipur", "Bhilai", "Bilaspur", "Durg"],
      govtColleges: 40,
      pvtColleges: 130,
      universities: 18,
      medicalColleges: 14,
      topColleges: ["AIIMS Raipur", "Pt. JNM Medical College", "NIT Raipur", "IIT Bhilai"],
      popularCourses: ["MBBS", "B.Tech Mining/Met", "BAMS", "B.Sc Nursing", "B.Pharm"],
      counsellingBody: "CG DME / CG Vyapam",
      highlights: "Strategic neighbour to MP with premier AIIMS Raipur campus and low-competition medical seats."
    },
    {
      id: "punjab",
      name: "Punjab",
      type: "State",
      code: "PB",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Ludhiana", "Amritsar", "Patiala", "Jalandhar", "Bathinda"],
      govtColleges: 55,
      pvtColleges: 220,
      universities: 30,
      medicalColleges: 12,
      topColleges: ["GMC Amritsar", "AIIMS Bathinda", "CMC Ludhiana", "Thapar Institute", "IIT Ropar"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Agriculture (PAU)", "B.Sc Nursing", "Hotel Mgmt"],
      counsellingBody: "BFUHS Punjab",
      highlights: "Agritech, medical research hubs and top-ranked private universities."
    },
    {
      id: "haryana",
      name: "Haryana",
      type: "State",
      code: "HR",
      image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
      cities: ["Gurugram", "Rohtak", "Faridabad", "Sonipat", "Ambala"],
      govtColleges: 50,
      pvtColleges: 210,
      universities: 34,
      medicalColleges: 15,
      topColleges: ["PGIMS Rohtak", "Ashoka University", "O.P. Jindal Global Law", "BPS Govt Medical"],
      popularCourses: ["MBBS", "Law (BA LLB)", "B.Tech", "B.Sc Sports", "BBA"],
      counsellingBody: "DMER Haryana / HSTES",
      highlights: "Proximity to Delhi NCR with leading private universities and PGIMS Rohtak."
    },
    {
      id: "odisha",
      name: "Odisha",
      type: "State",
      code: "OD",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur"],
      govtColleges: 52,
      pvtColleges: 190,
      universities: 28,
      medicalColleges: 16,
      topColleges: ["SCB Medical College", "AIIMS Bhubaneswar", "KIIT", "IIT Bhubaneswar", "NIT Rourkela"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Nursing", "B.Pharm", "MCA"],
      counsellingBody: "OJEE / DMET Odisha",
      highlights: "Bhubaneswar is Eastern India's education city with AIIMS and prominent multi-specialty colleges."
    },
    {
      id: "jharkhand",
      name: "Jharkhand",
      type: "State",
      code: "JH",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Deoghar"],
      govtColleges: 38,
      pvtColleges: 120,
      universities: 22,
      medicalColleges: 9,
      topColleges: ["RIMS Ranchi", "AIIMS Deoghar", "IIT ISM Dhanbad", "XLRI Jamshedpur", "BIT Mesra"],
      popularCourses: ["MBBS", "B.Tech", "MBA (XLRI)", "B.Sc Nursing", "Polytechnic"],
      counsellingBody: "JCECEB Jharkhand",
      highlights: "Mineral & industrial hub with RIMS Ranchi and AIIMS Deoghar offering quality medical education."
    },
    {
      id: "uttarakhand",
      name: "Uttarakhand",
      type: "State",
      code: "UK",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Dehradun", "Rishikesh", "Haridwar", "Haldwani", "Roorkee"],
      govtColleges: 35,
      pvtColleges: 160,
      universities: 26,
      medicalColleges: 10,
      topColleges: ["AIIMS Rishikesh", "IIT Roorkee", "Himalayan Institute (HIHT)", "UPES Dehradun", "GMC Haldwani"],
      popularCourses: ["MBBS", "Ayurveda", "Aviation & CPL", "B.Tech", "Hotel Management"],
      counsellingBody: "HNBUMU Uttarakhand",
      highlights: "Serene Himalayan learning hub famous for AIIMS Rishikesh, Yoga/Ayurveda, and boarding colleges."
    },
    {
      id: "himachal-pradesh",
      name: "Himachal Pradesh",
      type: "State",
      code: "HP",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Shimla", "Kangra", "Mandi", "Solan", "Bilaspur"],
      govtColleges: 30,
      pvtColleges: 90,
      universities: 20,
      medicalColleges: 8,
      topColleges: ["IGMC Shimla", "AIIMS Bilaspur", "RPGMC Tanda", "IIT Mandi", "Jaypee Solan"],
      popularCourses: ["MBBS", "BAMS", "B.Tech", "Pharmacy", "Tourism"],
      counsellingBody: "AMRU Himachal Pradesh",
      highlights: "Clean mountain learning environment with premier IGMC Shimla and AIIMS Bilaspur."
    },
    {
      id: "assam",
      name: "Assam",
      type: "State",
      code: "AS",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Guwahati", "Dibrugarh", "Silchar", "Jorhat"],
      govtColleges: 45,
      pvtColleges: 85,
      universities: 22,
      medicalColleges: 13,
      topColleges: ["Gauhati Medical College", "AIIMS Guwahati", "Assam Medical College", "IIT Guwahati"],
      popularCourses: ["MBBS", "B.Tech", "B.Sc Nursing", "Tea Management", "Pharmacy"],
      counsellingBody: "DME Assam",
      highlights: "Gateway to North-East India with IIT Guwahati and 13 rapidly growing medical institutes."
    },
    {
      id: "arunachal-pradesh",
      name: "Arunachal Pradesh",
      type: "State",
      code: "AR",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Itanagar", "Naharlagun", "Pasighat"],
      govtColleges: 15,
      pvtColleges: 25,
      universities: 8,
      medicalColleges: 2,
      topColleges: ["TRIHMS Naharlagun", "NERIST", "NIT Arunachal Pradesh"],
      popularCourses: ["MBBS", "Diploma Engg", "B.Sc Forestry", "B.Ed"],
      counsellingBody: "DHTE Arunachal Pradesh",
      highlights: "State-of-the-art TRIHMS medical college and central institutes with reserved quotas."
    },
    {
      id: "goa",
      name: "Goa",
      type: "State",
      code: "GA",
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
      cities: ["Panaji", "Margao", "Vasco da Gama"],
      govtColleges: 14,
      pvtColleges: 30,
      universities: 4,
      medicalColleges: 2,
      topColleges: ["Goa Medical College (Bambolim)", "BITS Goa", "IIT Goa", "Goa Institute of Management (GIM)"],
      popularCourses: ["MBBS", "MBA (GIM)", "B.Tech", "Hotel Management", "Marine Science"],
      counsellingBody: "DTE Goa",
      highlights: "Oldest medical college in Asia under Portuguese era (1691). World-class hospitality and B-schools."
    },
    {
      id: "manipur",
      name: "Manipur",
      type: "State",
      code: "MN",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Imphal", "Churachandpur"],
      govtColleges: 20,
      pvtColleges: 35,
      universities: 7,
      medicalColleges: 3,
      topColleges: ["RIMS Imphal", "JNIMS Imphal", "IIIT Manipur"],
      popularCourses: ["MBBS", "Sports Science", "B.Sc Nursing", "B.Tech"],
      counsellingBody: "DME Manipur",
      highlights: "Home to Regional Institute of Medical Sciences (RIMS) and National Sports University."
    },
    {
      id: "meghalaya",
      name: "Meghalaya",
      type: "State",
      code: "ML",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Shillong", "Tura"],
      govtColleges: 18,
      pvtColleges: 30,
      universities: 9,
      medicalColleges: 2,
      topColleges: ["NEIGRIHMS Shillong", "IIM Shillong", "NIT Meghalaya"],
      popularCourses: ["MBBS", "MBA", "B.Sc Nursing", "Social Work"],
      counsellingBody: "NEIGRIHMS / MCC",
      highlights: "NEIGRIHMS super-specialty central medical institute and IIM Shillong."
    },
    {
      id: "mizoram",
      name: "Mizoram",
      type: "State",
      code: "MZ",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Aizawl", "Lunglei"],
      govtColleges: 14,
      pvtColleges: 20,
      universities: 4,
      medicalColleges: 1,
      topColleges: ["Zoram Medical College (ZMC Aizawl)", "Mizoram University", "NIT Mizoram"],
      popularCourses: ["MBBS", "B.Sc Nursing", "B.Tech", "General Degrees"],
      counsellingBody: "DHTE Mizoram",
      highlights: "ZMC Falkawn providing full-fledged MBBS training with modern labs."
    },
    {
      id: "nagaland",
      name: "Nagaland",
      type: "State",
      code: "NL",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Kohima", "Dimapur"],
      govtColleges: 16,
      pvtColleges: 25,
      universities: 5,
      medicalColleges: 1,
      topColleges: ["NIMSR Kohima (Nagaland Institute of Medical Sciences)", "Nagaland University", "NIT Nagaland"],
      popularCourses: ["MBBS", "B.Tech", "B.Ed", "Agriculture"],
      counsellingBody: "DTE Nagaland",
      highlights: "Brand new NIMSR Kohima medical college inaugurated under National Medical Commission."
    },
    {
      id: "sikkim",
      name: "Sikkim",
      type: "State",
      code: "SK",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Gangtok", "Namchi"],
      govtColleges: 10,
      pvtColleges: 18,
      universities: 6,
      medicalColleges: 1,
      topColleges: ["Sikkim Manipal Institute of Medical Sciences (SMIMS)", "Sikkim University", "NIT Sikkim"],
      popularCourses: ["MBBS", "B.Tech CSE", "B.Sc Nursing", "Hotel Management"],
      counsellingBody: "SMU / MCC",
      highlights: "Sikkim Manipal University offering renowned MBBS and healthcare degree programs."
    },
    {
      id: "tripura",
      name: "Tripura",
      type: "State",
      code: "TR",
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",
      cities: ["Agartala", "Udaipur"],
      govtColleges: 15,
      pvtColleges: 22,
      universities: 5,
      medicalColleges: 2,
      topColleges: ["AGMC Agartala", "Tripura Medical College (TMC)", "NIT Agartala"],
      popularCourses: ["MBBS", "B.Tech", "B.Pharm", "B.Sc Nursing"],
      counsellingBody: "DME Tripura",
      highlights: "Agartala Government Medical College & TMC offering complete clinical training."
    },

    // --- 8 UNION TERRITORIES ---
    {
      id: "chandigarh",
      name: "Chandigarh",
      type: "Union Territory",
      code: "CH",
      image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
      cities: ["Chandigarh City"],
      govtColleges: 12,
      pvtColleges: 20,
      universities: 4,
      medicalColleges: 2,
      topColleges: ["PGIMER Chandigarh (NIRF #2)", "GMCH Sector 32", "Panjab University (PU)", "PEC Chandigarh"],
      popularCourses: ["MD/MS (PGIMER)", "MBBS", "B.Tech", "Law", "Pharmacy"],
      counsellingBody: "MCC / GMCH Joint Admissions",
      highlights: "Apex PGIMER medical institute and GMCH-32 in the planned city."
    },
    {
      id: "puducherry",
      name: "Puducherry",
      type: "Union Territory",
      code: "PY",
      image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
      cities: ["Puducherry", "Karaikal"],
      govtColleges: 15,
      pvtColleges: 35,
      universities: 6,
      medicalColleges: 9,
      topColleges: ["JIPMER (NIRF #4)", "IGMCRI", "PIMS Pondicherry", "Sri Manakula Vinayagar"],
      popularCourses: ["MBBS (JIPMER)", "BDS", "Allied Health", "B.Tech", "B.Sc Nursing"],
      counsellingBody: "CENTAC Puducherry / MCC",
      highlights: "Institute of National Importance JIPMER and rich medical coastal colleges."
    },
    {
      id: "jammu-kashmir",
      name: "Jammu & Kashmir",
      type: "Union Territory",
      code: "JK",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
      govtColleges: 35,
      pvtColleges: 50,
      universities: 12,
      medicalColleges: 12,
      topColleges: ["SKIMS Soura", "GMC Srinagar", "GMC Jammu", "AIIMS Vijaypur (Jammu)", "NIT Srinagar"],
      popularCourses: ["MBBS", "B.Tech", "Ayush", "B.Sc Nursing", "B.Ed"],
      counsellingBody: "JKBOPEE / MCC",
      highlights: "Historic medical colleges and brand new AIIMS Jammu campus."
    },
    {
      id: "ladakh",
      name: "Ladakh",
      type: "Union Territory",
      code: "LA",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&auto=format&fit=crop&q=80",
      cities: ["Leh", "Kargil"],
      govtColleges: 6,
      pvtColleges: 8,
      universities: 2,
      medicalColleges: 1,
      topColleges: ["University of Ladakh", "Govt Degree College Leh", "Proposed Medical College Leh"],
      popularCourses: ["Sowa-Rigpa (Traditional Medicine)", "B.Sc Geology", "Tourism", "BA"],
      counsellingBody: "Central Universities / Ladakh Admin",
      highlights: "National Institute of Sowa-Rigpa and specialized high-altitude environmental research."
    },
    {
      id: "andaman-nicobar",
      name: "Andaman & Nicobar Islands",
      type: "Union Territory",
      code: "AN",
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
      cities: ["Port Blair"],
      govtColleges: 6,
      pvtColleges: 4,
      universities: 1,
      medicalColleges: 1,
      topColleges: ["ANIIMS Port Blair (Andaman Medical College)", "JNRM Port Blair", "DBRAIT"],
      popularCourses: ["MBBS", "Marine Biology", "Oceanography", "B.Tech"],
      counsellingBody: "ANIIMS / MCC",
      highlights: "ANIIMS Port Blair surrounded by rich marine ecosystems."
    },
    {
      id: "dadra-nagar-haveli-daman-diu",
      name: "Dadra & Nagar Haveli and Daman & Diu",
      type: "Union Territory",
      code: "DNHDD",
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
      cities: ["Silvassa", "Daman", "Diu"],
      govtColleges: 8,
      pvtColleges: 10,
      universities: 1,
      medicalColleges: 1,
      topColleges: ["NAMO Medical Education & Research Institute (Silvassa)", "Govt College Daman"],
      popularCourses: ["MBBS", "Polytechnic", "B.Com", "B.Sc Chemistry"],
      counsellingBody: "MCC / UT Administration",
      highlights: "Modern NAMO Medical Institute in Silvassa with 177 MBBS seats."
    },
    {
      id: "lakshadweep",
      name: "Lakshadweep",
      type: "Union Territory",
      code: "LD",
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
      cities: ["Kavaratti", "Andrott", "Kadmat"],
      govtColleges: 4,
      pvtColleges: 2,
      universities: 1,
      medicalColleges: 0,
      topColleges: ["Calicut University Centre Kavaratti", "Govt College Andrott"],
      popularCourses: ["Marine Fisheries", "Aquaculture", "B.Sc", "B.Com"],
      counsellingBody: "Central Quota / Lakshadweep Admin",
      highlights: "Reserved AIQ medical & professional seats in Kerala/Goa colleges for island students."
    }
  ],

  // =========================================================================
  // 2. DEDICATED MEDICAL COURSE BOXES (MBBS, BHMS, BAMS, BUMS, MD/MS)
  // =========================================================================
  medicalBoxes: [
    {
      id: "mbbs",
      name: "MBBS",
      fullName: "Bachelor of Medicine & Bachelor of Surgery",
      badge: "Apex Allopathic Degree",
      icon: "fa-solid fa-user-doctor",
      color: "#0284c7",
      bgColor: "#e0f2fe",
      duration: "5.5 Years (4.5 Yrs Academic + 1 Yr Compulsory Rotating Internship)",
      eligibility: "10+2 with Physics, Chemistry, Biology (PCB) & English with min 50% marks (40% for SC/ST/OBC). Must be NEET-UG Qualified.",
      neetRequirement: "Mandatory NEET-UG Qualification. Cutoff varies: 600+ for Top Govt, 520+ for State Govt, 250-450 for Pvt/Deemed.",
      feesGovt: "₹5,000 – ₹1.5 Lakh / year",
      feesPvt: "₹8 Lakh – ₹18 Lakh / year",
      feesDeemed: "₹18 Lakh – ₹26 Lakh / year",
      seatsIndia: "1,08,000+ MBBS Seats across 700+ Medical Colleges in India",
      counsellingBodies: ["MCC (15% AIQ + 100% Deemed/Central)", "State DME / DTE (85% State Quota)"],
      careerScope: ["Hospital Physician", "Medical Officer (UPSC CMS / State PSC)", "Specialist Surgeon (via NEET-PG)", "Defense Medical Officer (AFMS)", "International Practice (USMLE / PLAB)"],
      documentsRequired: ["NEET Admit Card & Scorecard", "10th & 12th Marksheets", "Domicile Certificate", "Caste & Income Certificate", "Aadhaar Card", "Provisional Allotment Letter"]
    },
    {
      id: "bds",
      name: "BDS",
      fullName: "Bachelor of Dental Surgery",
      badge: "Apex Dental Surgery & Oral Healthcare",
      icon: "fa-solid fa-tooth",
      color: "#0d9488",
      bgColor: "#ccfbf1",
      duration: "5 Years (4 Years Academic + 1 Year Compulsory Paid Rotatory Internship)",
      eligibility: "10+2 with Physics, Chemistry, Biology/Biotechnology & English with min 50% marks (40% for SC/ST/OBC). Must qualify NEET-UG entrance exam.",
      neetRequirement: "Mandatory NEET-UG Qualification. Cutoff range: 520-590+ for Govt Dental Colleges; 140-350 marks for Private & Deemed Dental Colleges.",
      feesGovt: "₹25,000 – ₹70,000 / year (State & Central Govt Dental Colleges)",
      feesPvt: "₹2.5 Lakh – ₹5.0 Lakh / year (State Merit / FRA Regulated)",
      feesDeemed: "₹4.5 Lakh – ₹7.5 Lakh / year (MCC Deemed University AIQ)",
      seatsIndia: "27,800+ BDS Seats across 320+ Dental Colleges in India",
      counsellingBodies: [
        "MCC (15% All India Quota in Govt Dental + 100% Deemed Universities / Central Universities like BHU, Jamia)",
        "State Counselling Authorities (85% State Quota - MP DME, Maharashtra CET Cell, UP DGME)"
      ],
      careerScope: [
        "Dental Surgeon & Private Clinical Practice",
        "Government Dental Officer (Army Dental Corps / Railways / State PSC / ESI Hospitals)",
        "Specialist Master in Dental Surgery (MDS via NEET-MDS in Orthodontics, Oral & Maxillofacial Surgery, Endodontics, Prosthodontics)",
        "Aesthetic & Cosmetic Dentistry, Oral Implantology Specialist",
        "International Licensure Practice (NBDE USA, ORE UK, ADC Australia, DHA Dubai)"
      ],
      documentsRequired: [
        "NEET-UG Admit Card & Scorecard",
        "10th & 12th Board Marksheets & Passing Certificates",
        "State Domicile Certificate (for 85% State Quota seats)",
        "Caste & EWS Certificate (if applicable)",
        "Aadhaar Card / ID Proof",
        "Provisional Allotment Letter & Verification Slip"
      ]
    },
    {
      id: "bams",
      name: "BAMS",
      fullName: "Bachelor of Ayurvedic Medicine & Surgery",
      badge: "Holistic Herbal Medicine",
      icon: "fa-solid fa-leaf",
      color: "#059669",
      bgColor: "#d1fae5",
      duration: "5.5 Years (4.5 Yrs Study + 1 Yr Clinical Internship)",
      eligibility: "10+2 with PCB (min 50% for UR, 40% for Reserved). Mandatory NEET-UG Qualification.",
      neetRequirement: "NEET-UG score based. Govt cutoff ~400-520 marks; Private colleges accept qualifying NEET score.",
      feesGovt: "₹20,000 – ₹80,000 / year",
      feesPvt: "₹2.0 Lakh – ₹4.5 Lakh / year",
      feesDeemed: "₹4.5 Lakh – ₹7.5 Lakh / year",
      seatsIndia: "35,000+ BAMS Seats in 450+ Ayurveda Medical Colleges",
      counsellingBodies: ["AACCC (15% All India AYUSH Quota)", "State AYUSH Counselling Authorities (MP AYUSH, UP AYUSH)"],
      careerScope: ["Ayurvedic Medical Officer (Govt Clinics)", "Panchakarma Center Director", "Pharma R&D (Dabur, Himalaya, Patanjali)", "Wellness Consultant", "MD/MS Ayurveda Specialist"],
      documentsRequired: ["NEET Scorecard", "12th Science Marksheet", "Domicile Certificate", "Caste Certificate (if applicable)", "Passport Photos"]
    },
    {
      id: "bhms",
      name: "BHMS",
      fullName: "Bachelor of Homoeopathic Medicine & Surgery",
      badge: "Alternative Gentle Healing",
      icon: "fa-solid fa-dna",
      color: "#9333ea",
      bgColor: "#f3e8ff",
      duration: "5.5 Years (4.5 Yrs Classroom & Hospital Training + 1 Yr Internship)",
      eligibility: "10+2 with Physics, Chemistry & Biology. Must qualify NEET-UG entrance examination.",
      neetRequirement: "NEET-UG Qualified score (UR: 50th percentile, Reserved: 40th percentile).",
      feesGovt: "₹15,000 – ₹60,000 / year",
      feesPvt: "₹1.5 Lakh – ₹3.5 Lakh / year",
      feesDeemed: "₹3.5 Lakh – ₹5.5 Lakh / year",
      seatsIndia: "18,000+ Seats across 280+ Homoeopathy Medical Colleges",
      counsellingBodies: ["AACCC (All India AYUSH)", "State Ayush Counselling Committee"],
      careerScope: ["Homeopathic Physician", "Govt Homeopathic Medical Officer", "Private Clinic Consultant", "Research Officer (CCRH)", "Public Health Specialist"],
      documentsRequired: ["NEET Admit Card", "Marksheets", "Aadhaar Card", "Transfer Certificate", "Income Certificate"]
    },
    {
      id: "bums",
      name: "BUMS",
      fullName: "Bachelor of Unani Medicine & Surgery",
      badge: "Traditional Greco-Arabic Medicine",
      icon: "fa-solid fa-mortar-pestle",
      color: "#d97706",
      bgColor: "#fef3c7",
      duration: "5.5 Years (4.5 Yrs Study + 1 Yr Internship)",
      eligibility: "10+2 with PCB (50%+) + Urdu / Arabic language passed in 10th or 12th standard. NEET-UG Qualified.",
      neetRequirement: "NEET-UG qualification with Urdu knowledge requirement.",
      feesGovt: "₹10,000 – ₹50,000 / year",
      feesPvt: "₹1.2 Lakh – ₹3.0 Lakh / year",
      feesDeemed: "₹3.0 Lakh – ₹4.5 Lakh / year",
      seatsIndia: "3,500+ Seats in 60+ Unani Colleges",
      counsellingBodies: ["AACCC Central AYUSH", "State Ayush Counselling Boards"],
      careerScope: ["Hakim / Unani Medical Practitioner", "Unani Pharmacist", "Clinical Researcher (CCRUM)", "Hospital Consultant"],
      documentsRequired: ["NEET Scorecard", "10th Urdu Certificate", "12th Marksheet", "Domicile Certificate"]
    },
    {
      id: "bnys",
      name: "BNYS",
      fullName: "Bachelor of Naturopathy & Yogic Sciences",
      badge: "Drugless Healthcare & Lifestyle Medicine",
      icon: "fa-solid fa-spa",
      color: "#0891b2",
      bgColor: "#cffafe",
      duration: "5.5 Years (4.5 Yrs Academic & Hospital Training + 1 Yr Rotatory Internship)",
      eligibility: "10+2 with Physics, Chemistry & Biology (PCB) with minimum 50% marks (40% for SC/ST/OBC).",
      neetRequirement: "NEET-UG qualification or State AYUSH Entrance / Merit based admission (State dependent).",
      feesGovt: "₹15,000 – ₹50,000 / year (Govt Naturopathy & Yoga Colleges)",
      feesPvt: "₹1.2 Lakh – ₹2.5 Lakh / year (State Merit / Regulated)",
      feesDeemed: "₹2.5 Lakh – ₹4.0 Lakh / year (Private / Deemed Universities)",
      seatsIndia: "5,500+ BNYS Seats across 80+ Naturopathy Medical Colleges in India",
      counsellingBodies: [
        "Ministry of AYUSH (Central Guidelines)",
        "State AYUSH Counselling Authorities (MP AYUSH, UP AYUSH, Karnataka KEA, TN Medical, Gujarat AYUSH)"
      ],
      careerScope: [
        "Registered Naturopathic Physician & Clinic Director (Eligible for 'Dr.' Title)",
        "Chief Medical Officer in AYUSH, Naturopathy & Wellness Hospitals",
        "Clinical Lifestyle Medicine & Therapeutic Yoga Consultant",
        "Acupuncture, Hydrotherapy & Dietetics Specialist",
        "Academic Professor & Researcher (CCRYN / National Institute of Naturopathy - NIN Pune)",
        "International Holistic Health Specialist (Europe, Middle East, USA, Australia, SE Asia)"
      ],
      documentsRequired: [
        "10th & 12th Marksheets & Passing Certificates",
        "NEET Scorecard (if applicable) / State Entrance Rank Card",
        "Domicile & Nationality Certificate",
        "Caste / EWS & Income Certificate (if applicable)",
        "Aadhaar Card & Identity Proof",
        "Medical Fitness Certificate & Passport Photos"
      ]
    },
    {
      id: "md-ms",
      name: "MD / MS",
      fullName: "Doctor of Medicine (MD) & Master of Surgery (MS)",
      badge: "Apex Post-Graduate Medical Specialization",
      icon: "fa-solid fa-microscope",
      color: "#e11d48",
      bgColor: "#ffe4e6",
      duration: "3 Years Residency Program",
      eligibility: "MBBS Degree recognized by NMC + Permanent/Provisional NMC Registration + Completed 1-Yr Internship. Must qualify NEET-PG / INICET.",
      neetRequirement: "NEET-PG Rank / Score (High rank required for Radio, Derma, Medicine, Ortho).",
      feesGovt: "₹20,000 – ₹1.2 Lakh / year (with ₹60k-₹1.1L/mo Stipend)",
      feesPvt: "₹15 Lakh – ₹35 Lakh / year",
      feesDeemed: "₹25 Lakh – ₹45 Lakh / year (Management / NRI Quota)",
      seatsIndia: "45,000+ PG Seats (MD, MS, DNB, Diploma) in Clinical & Non-Clinical branches",
      counsellingBodies: ["MCC (50% AIQ + 100% Deemed)", "State DME (50% State Quota)"],
      careerScope: ["Super-specialist Consultant", "Chief Surgeon", "Head of Clinical Department", "Medical College Professor", "Fellowship / DM / M.Ch Aspirant"],
      documentsRequired: ["NEET PG Scorecard", "MBBS Degree & Attempt Certificate", "NMC/State Medical Council Registration", "Internship Completion Certificate", "SMC Domicile Proof"]
    }
  ],

  // =========================================================================
  // 3. 25+ CAREER CATEGORIES (500+ COURSES)
  // =========================================================================
  categories: [
    {
      id: "medical-dental",
      name: "Medical & Dental",
      count: "25+ Courses",
      icon: "fa-solid fa-user-doctor",
      color: "#0284c7",
      bgColor: "#e0f2fe",
      description: "MBBS, BDS, Post-Graduate MD/MS, Dental Hygiene, Implantology and specialized clinical careers.",
      topExams: ["NEET-UG", "NEET-PG", "INICET", "MDS"],
      courses: [
        { name: "MBBS (Bachelor of Medicine & Surgery)", duration: "5.5 Years", eligibility: "10+2 with PCB (50%+) + NEET UG", avgFee: "₹10K - ₹25L/yr", scope: "Doctor, Physician, Surgeon, Medical Officer" },
        { name: "BDS (Bachelor of Dental Surgery)", duration: "5 Years", eligibility: "10+2 with PCB + NEET UG", avgFee: "₹1L - ₹8L/yr", scope: "Dental Surgeon, Orthodontist, Periodontist" },
        { name: "MD (Doctor of Medicine) - General Medicine/Pediatrics/Radio", duration: "3 Years", eligibility: "MBBS + NEET PG", avgFee: "₹30K - ₹35L/yr", scope: "Specialist Consultant, Hospital Head" },
        { name: "MS (Master of Surgery) - Ortho/General/ENT/Ophthal", duration: "3 Years", eligibility: "MBBS + NEET PG", avgFee: "₹40K - ₹40L/yr", scope: "Chief Surgeon, Specialist" },
        { name: "MDS (Master of Dental Surgery)", duration: "3 Years", eligibility: "BDS + NEET MDS", avgFee: "₹2L - ₹15L/yr", scope: "Maxillofacial Surgeon, Prosthodontist" },
        { name: "Diploma in Dental Hygiene", duration: "2 Years", eligibility: "10+2 with PCB", avgFee: "₹40K - ₹1.5L/yr", scope: "Certified Dental Hygienist" }
      ]
    },
    {
      id: "ayush",
      name: "AYUSH (Alternative Medicine)",
      count: "15+ Courses",
      icon: "fa-solid fa-leaf",
      color: "#059669",
      bgColor: "#d1fae5",
      description: "BAMS, BHMS, BUMS, BSMS, BNYS, Panchakarma, Naturopathy and holistic healing medical streams.",
      topExams: ["NEET-UG (AYUSH)", "AIAPGET"],
      courses: [
        { name: "BAMS (Bachelor of Ayurvedic Medicine & Surgery)", duration: "5.5 Years", eligibility: "10+2 PCB + NEET UG", avgFee: "₹50K - ₹4.5L/yr", scope: "Ayurvedic Doctor, Medical Officer, Wellness Director" },
        { name: "BHMS (Bachelor of Homeopathic Medicine & Surgery)", duration: "5.5 Years", eligibility: "10+2 PCB + NEET UG", avgFee: "₹40K - ₹3.5L/yr", scope: "Homeopathic Physician, Consultant" },
        { name: "BUMS (Bachelor of Unani Medicine & Surgery)", duration: "5.5 Years", eligibility: "10+2 PCB + Urdu + NEET", avgFee: "₹30K - ₹2.5L/yr", scope: "Hakim, Unani Medical Officer" },
        { name: "BNYS (Bachelor of Naturopathy & Yogic Sciences)", duration: "5.5 Years", eligibility: "10+2 PCB (NEET/Direct)", avgFee: "₹60K - ₹3L/yr", scope: "Naturopathy Physician, Yoga Doctor" }
      ]
    },
    {
      id: "nursing",
      name: "Nursing",
      count: "15+ Courses",
      icon: "fa-solid fa-user-nurse",
      color: "#db2777",
      bgColor: "#fce7f3",
      description: "B.Sc Nursing, GNM, ANM, M.Sc Nursing, Post Basic B.Sc and critical care clinical training.",
      topExams: ["State Nursing CETs", "AIIMS Nursing", "NEET-UG"],
      courses: [
        { name: "B.Sc Nursing", duration: "4 Years", eligibility: "10+2 PCB (45%+)", avgFee: "₹40K - ₹2.5L/yr", scope: "Staff Nurse, Military Nursing, ICU Specialist, Abroad (NCLEX)" },
        { name: "GNM (General Nursing and Midwifery)", duration: "3.5 Years", eligibility: "10+2 Any Stream (40%+)", avgFee: "₹35K - ₹1.5L/yr", scope: "Staff Nurse, Community Health Worker" },
        { name: "ANM (Auxiliary Nursing Midwifery)", duration: "2 Years", eligibility: "10+2 Any Stream (Females)", avgFee: "₹20K - ₹80K/yr", scope: "Rural Health Worker, Primary Health Nurse" }
      ]
    },
    {
      id: "allied-health",
      name: "Allied Health / Paramedical",
      count: "50+ Courses",
      icon: "fa-solid fa-heart-pulse",
      color: "#0891b2",
      bgColor: "#cffafe",
      description: "BPT, BOT, BMLT, BMRIT, OTT, Dialysis Tech, BASLP, Cardiac Care and Emergency Medicine.",
      topExams: ["State Paramedical Entrance", "Direct Merit"],
      courses: [
        { name: "BPT (Bachelor of Physiotherapy)", duration: "4.5 Years", eligibility: "10+2 PCB (50%+)", avgFee: "₹50K - ₹2.5L/yr", scope: "Physiotherapist, Sports Rehab Consultant" },
        { name: "BMLT (Medical Laboratory Technology)", duration: "3 Years", eligibility: "10+2 PCB", avgFee: "₹35K - ₹1.5L/yr", scope: "Chief Lab Technologist, Diagnostic Centers" },
        { name: "BMRIT (Medical Radiography & Imaging)", duration: "3 Years", eligibility: "10+2 PCB", avgFee: "₹50K - ₹2L/yr", scope: "MRI / CT Scan Specialist" },
        { name: "B.Sc Operation Theatre Technology (OTT)", duration: "3 Years", eligibility: "10+2 PCB", avgFee: "₹40K - ₹1.8L/yr", scope: "OT Technologist in Hospitals" }
      ]
    },
    {
      id: "pharmacy",
      name: "Pharmacy",
      count: "15+ Courses",
      icon: "fa-solid fa-capsules",
      color: "#16a34a",
      bgColor: "#dcfce7",
      description: "D.Pharm, B.Pharm, M.Pharm, Pharm.D (Doctor of Pharmacy) and Drug Regulatory Affairs.",
      topExams: ["GPAT", "CUET-UG", "State Pharmacy CET"],
      courses: [
        { name: "B.Pharm (Bachelor of Pharmacy)", duration: "4 Years", eligibility: "10+2 PCM/PCB (50%+)", avgFee: "₹50K - ₹2L/yr", scope: "Pharmacist, Drug Inspector, Pharma QA/QC" },
        { name: "D.Pharm (Diploma in Pharmacy)", duration: "2 Years", eligibility: "10+2 PCM/PCB", avgFee: "₹35K - ₹1.2L/yr", scope: "Retail Chemist, Hospital Pharmacist" },
        { name: "Pharm.D (Doctor of Pharmacy)", duration: "6 Years", eligibility: "10+2 PCB/PCM", avgFee: "₹1.5L - ₹4.5L/yr", scope: "Clinical Pharmacist, Clinical Trials Specialist" }
      ]
    },
    {
      id: "engineering",
      name: "Engineering & Technology",
      count: "60+ Courses",
      icon: "fa-solid fa-gear",
      color: "#2563eb",
      bgColor: "#dbeafe",
      description: "B.Tech/B.E in CSE, AI & ML, Robotics, Mechanical, Civil, ECE, Aerospace, Data Science & Cyber Security.",
      topExams: ["JEE Main", "JEE Advanced", "State CETs"],
      courses: [
        { name: "B.Tech in Computer Science & Engineering (CSE)", duration: "4 Years", eligibility: "10+2 PCM + Entrance", avgFee: "₹60K - ₹4L/yr", scope: "Software Engineer, Full Stack Dev, Cloud Architect" },
        { name: "B.Tech in AI & Machine Learning (AI/ML)", duration: "4 Years", eligibility: "10+2 PCM", avgFee: "₹75K - ₹4.5L/yr", scope: "AI Engineer, ML Scientist" },
        { name: "B.Tech in Cyber Security & Forensics", duration: "4 Years", eligibility: "10+2 PCM", avgFee: "₹70K - ₹3.8L/yr", scope: "Security Analyst, Penetration Tester" }
      ]
    },
    {
      id: "polytechnic",
      name: "Polytechnic / Diploma",
      count: "30+ Courses",
      icon: "fa-solid fa-wrench",
      color: "#d97706",
      bgColor: "#fef3c7",
      description: "3-Year Diploma in Civil, Mechanical, Electrical, Computer, Automobile, Mining & Chemical Engineering.",
      topExams: ["State Polytechnic PPT", "10th Merit"],
      courses: [
        { name: "Diploma in Mechanical Engineering", duration: "3 Years", eligibility: "10th Pass (35%+)", avgFee: "₹15K - ₹60K/yr", scope: "Junior Engineer (JE), Plant Supervisor" },
        { name: "Diploma in Civil Engineering", duration: "3 Years", eligibility: "10th Pass", avgFee: "₹15K - ₹60K/yr", scope: "Site Engineer, PWD/Govt JE" }
      ]
    },
    {
      id: "computer-it",
      name: "Computer & IT",
      count: "40+ Courses",
      icon: "fa-solid fa-laptop-code",
      color: "#7c3aed",
      bgColor: "#ede9fe",
      description: "BCA, MCA, B.Sc Computer Science, B.Sc IT, Cloud Computing, Full Stack & Game Development.",
      topExams: ["NIMCET", "CUET-UG/PG"],
      courses: [
        { name: "BCA (Bachelor of Computer Applications)", duration: "3 Years", eligibility: "10+2 Any Stream with Maths/CS", avgFee: "₹30K - ₹1.8L/yr", scope: "Software Developer, Frontend/Backend, QA Engineer" },
        { name: "MCA (Master of Computer Applications)", duration: "2 Years", eligibility: "BCA / Graduation with Maths", avgFee: "₹50K - ₹2.5L/yr", scope: "System Architect, Lead Software Engineer" }
      ]
    },
    {
      id: "management",
      name: "Management & Business",
      count: "30+ Courses",
      icon: "fa-solid fa-briefcase",
      color: "#0d9488",
      bgColor: "#ccfbf1",
      description: "BBA, MBA, PGDM, BMS, BBM, HR, Marketing, Finance, Business Analytics & Entrepreneurship.",
      topExams: ["CAT", "MAT", "CMAT", "CUET"],
      courses: [
        { name: "MBA (Master of Business Administration)", duration: "2 Years", eligibility: "Graduation (50%+) + CAT/CMAT", avgFee: "₹80K - ₹8L/yr", scope: "Brand Manager, Financial Analyst, HR Director" },
        { name: "BBA (Bachelor of Business Administration)", duration: "3 Years", eligibility: "10+2 Any Stream (50%+)", avgFee: "₹40K - ₹2.5L/yr", scope: "Business Development, Marketing Executive" }
      ]
    },
    {
      id: "commerce-finance",
      name: "Commerce & Finance",
      count: "25+ Courses",
      icon: "fa-solid fa-coins",
      color: "#b45309",
      bgColor: "#fef3c7",
      description: "B.Com, M.Com, CA (Chartered Accountancy), CS, CMA, Banking, Financial Markets.",
      topExams: ["CA Foundation", "CS EET", "CMA"],
      courses: [
        { name: "B.Com (Hons / Plain)", duration: "3 Years", eligibility: "10+2 Commerce/Science", avgFee: "₹15K - ₹1.2L/yr", scope: "Accountant, Tax Consultant, Financial Analyst" },
        { name: "Chartered Accountancy (CA - ICAI)", duration: "4 - 5 Years", eligibility: "10+2 or Graduation", avgFee: "₹40K - ₹1.5L", scope: "Statutory Auditor, CFO, Tax Head" }
      ]
    },
    {
      id: "law",
      name: "Law & Legal Studies",
      count: "20+ Courses",
      icon: "fa-solid fa-scale-balanced",
      color: "#4f46e5",
      bgColor: "#e0e7ff",
      description: "LLB (3-Yr), BA LLB, BBA LLB (5-Yr Integrated), LLM, Cyber Law & Corporate Law.",
      topExams: ["CLAT", "AILET", "State Law CET"],
      courses: [
        { name: "BA LLB (5-Year Integrated)", duration: "5 Years", eligibility: "10+2 Any Stream + CLAT/Entrance", avgFee: "₹50K - ₹3.5L/yr", scope: "Advocate, Corporate Lawyer, Judicial Officer" },
        { name: "LLB (3-Year Degree)", duration: "3 Years", eligibility: "Any Graduation (45%+)", avgFee: "₹25K - ₹1.8L/yr", scope: "Litigation Lawyer, Public Prosecutor" }
      ]
    },
    {
      id: "teaching-education",
      name: "Teaching & Education",
      count: "25+ Courses",
      icon: "fa-solid fa-chalkboard-user",
      color: "#ea580c",
      bgColor: "#ffedd5",
      description: "B.Ed, M.Ed, D.El.Ed, Integrated B.Sc B.Ed, B.P.Ed and CTET Guidance.",
      topExams: ["State B.Ed CET", "CTET"],
      courses: [
        { name: "B.Ed (Bachelor of Education)", duration: "2 Years", eligibility: "Graduation (50%+)", avgFee: "₹30K - ₹80K/yr", scope: "TGT / PGT Teacher, School Principal" },
        { name: "D.El.Ed (Diploma in Elementary Ed)", duration: "2 Years", eligibility: "10+2 Any Stream", avgFee: "₹20K - ₹50K/yr", scope: "Primary School Teacher (PRT)" }
      ]
    },
    {
      id: "science",
      name: "Science & Pure Research",
      count: "35+ Courses",
      icon: "fa-solid fa-flask-vial",
      color: "#0284c7",
      bgColor: "#e0f2fe",
      description: "B.Sc & M.Sc in Biotechnology, Microbiology, Physics, Chemistry, Mathematics & Life Sciences.",
      topExams: ["CUET-UG/PG", "IIT JAM"],
      courses: [
        { name: "B.Sc Biotechnology", duration: "3 Years", eligibility: "10+2 with PCB/PCM", avgFee: "₹30K - ₹1.5L/yr", scope: "Biotech Researcher, Pharma QC, Vaccine Scientist" },
        { name: "B.Sc Microbiology", duration: "3 Years", eligibility: "10+2 PCB", avgFee: "₹30K - ₹1.4L/yr", scope: "Microbiologist, Food Safety Officer" }
      ]
    },
    {
      id: "agriculture",
      name: "Agriculture & Agribusiness",
      count: "25+ Courses",
      icon: "fa-solid fa-wheat-awn",
      color: "#65a30d",
      bgColor: "#ecfccb",
      description: "B.Sc Agriculture (Hons), Horticulture, Forestry, Dairy Tech & Agribusiness Management.",
      topExams: ["ICAR AIEEA", "State PAT", "CUET"],
      courses: [
        { name: "B.Sc (Hons) Agriculture", duration: "4 Years", eligibility: "10+2 with PCB/PCM/Agri", avgFee: "₹25K - ₹1.8L/yr", scope: "Agriculture Development Officer, Bank AFO" },
        { name: "B.Tech Food Technology", duration: "4 Years", eligibility: "10+2 PCM/PCB", avgFee: "₹45K - ₹2.5L/yr", scope: "Food Safety Officer, Quality Lead" }
      ]
    },
    {
      id: "architecture-design",
      name: "Architecture & Planning",
      count: "15+ Courses",
      icon: "fa-solid fa-compass-drafting",
      color: "#475569",
      bgColor: "#f1f5f9",
      description: "B.Arch, M.Arch, B.Plan, Interior Design, Landscape Architecture.",
      topExams: ["NATA", "JEE Main Paper 2"],
      courses: [
        { name: "B.Arch (Bachelor of Architecture)", duration: "5 Years", eligibility: "10+2 PCM + NATA / JEE Paper 2", avgFee: "₹80K - ₹3.5L/yr", scope: "Architect, Urban Planner, Project Designer" }
      ]
    },
    {
      id: "design-fashion",
      name: "Design & Fashion",
      count: "25+ Courses",
      icon: "fa-solid fa-wand-magic-sparkles",
      color: "#c026d3",
      bgColor: "#fae8ff",
      description: "B.Des in UI/UX Design, Fashion Design, Graphic Design, 3D Animation & Game Art.",
      topExams: ["NIFT", "NID DAT", "UCEED"],
      courses: [
        { name: "B.Des in UI / UX Design", duration: "4 Years", eligibility: "10+2 Any Stream", avgFee: "₹80K - ₹4.5L/yr", scope: "UI/UX Designer, Product Designer" }
      ]
    },
    {
      id: "media-journalism",
      name: "Media & Journalism",
      count: "20+ Courses",
      icon: "fa-solid fa-microphone-lines",
      color: "#e11d48",
      bgColor: "#ffe4e6",
      description: "BJMC, Mass Communication, Film Making, Public Relations, Digital Media.",
      topExams: ["IIMC Entrance", "CUET-UG"],
      courses: [
        { name: "BJMC (Bachelor of Journalism & Mass Comm)", duration: "3 Years", eligibility: "10+2 Any Stream", avgFee: "₹35K - ₹1.8L/yr", scope: "News Anchor, Reporter, PR Specialist" }
      ]
    },
    {
      id: "hotel-tourism",
      name: "Hotel Management & Tourism",
      count: "20+ Courses",
      icon: "fa-solid fa-utensils",
      color: "#d97706",
      bgColor: "#fef3c7",
      description: "BHM, Culinary Arts, Travel & Tourism, Event Management.",
      topExams: ["NCHMCT JEE"],
      courses: [
        { name: "B.Sc in Hospitality & Hotel Administration (BHM)", duration: "3 Years", eligibility: "10+2 Any Stream + NCHMCT", avgFee: "₹60K - ₹2.5L/yr", scope: "Hotel Manager, Cruise Staff, F&B Lead" }
      ]
    },
    {
      id: "aviation",
      name: "Aviation & Pilot Training",
      count: "15+ Courses",
      icon: "fa-solid fa-plane-departure",
      color: "#0284c7",
      bgColor: "#e0f2fe",
      description: "Commercial Pilot License (CPL - DGCA), Cabin Crew, Airport Management.",
      topExams: ["DGCA Exams", "IGRUA"],
      courses: [
        { name: "Commercial Pilot License Training (CPL)", duration: "1.5 - 2 Years", eligibility: "10+2 Physics & Maths (50%+)", avgFee: "₹35L - ₹55L Total", scope: "Airline Pilot (Air India, IndiGo)" }
      ]
    },
    {
      id: "maritime-navy",
      name: "Maritime / Merchant Navy",
      count: "15+ Courses",
      icon: "fa-solid fa-anchor",
      color: "#0f766e",
      bgColor: "#ccfbf1",
      description: "B.Sc Nautical Science, B.Tech Marine Engineering, GP Rating.",
      topExams: ["IMU CET"],
      courses: [
        { name: "B.Sc Nautical Science (Deck Cadet)", duration: "3 Years", eligibility: "10+2 PCM (60%+) + IMU CET", avgFee: "₹2L - ₹4.5L/yr", scope: "Deck Officer, Ship Captain" }
      ]
    },
    {
      id: "arts-humanities",
      name: "Arts & Humanities",
      count: "40+ Courses",
      icon: "fa-solid fa-book-bookmark",
      color: "#7c2d12",
      bgColor: "#ffedd5",
      description: "BA in Political Science, Economics, History, Psychology, Civil Services Prep.",
      topExams: ["CUET-UG", "UPSC / State PSC"],
      courses: [
        { name: "BA (Hons) in Political Science", duration: "3 Years", eligibility: "10+2 Any Stream", avgFee: "₹10K - ₹80K/yr", scope: "Civil Services, Policy Analyst" }
      ]
    },
    {
      id: "social-psychology",
      name: "Social Work & Psychology",
      count: "15+ Courses",
      icon: "fa-solid fa-brain",
      color: "#9333ea",
      bgColor: "#f3e8ff",
      description: "BA/B.Sc Clinical Psychology, BSW, MSW, Counseling Psychology.",
      topExams: ["CUET-UG", "TISSNET"],
      courses: [
        { name: "BA / B.Sc Clinical Psychology", duration: "3 - 4 Years", eligibility: "10+2 Any Stream", avgFee: "₹30K - ₹1.8L/yr", scope: "Mental Health Counselor, Clinical Psychologist" }
      ]
    },
    {
      id: "vocational-iti",
      name: "Vocational / Skill / ITI",
      count: "50+ Courses",
      icon: "fa-solid fa-screwdriver-wrench",
      color: "#b45309",
      bgColor: "#fef3c7",
      description: "Electrician, Fitter, Welder, COPA, RAC, Solar Technician.",
      topExams: ["NCVT ITI Allotment"],
      courses: [
        { name: "ITI Electrician (NCVT)", duration: "2 Years", eligibility: "10th Pass with Maths & Science", avgFee: "₹5K - ₹35K/yr", scope: "Govt Railway Tech, Power Board Tech" }
      ]
    },
    {
      id: "animal-food",
      name: "Veterinary, Animal & Fisheries",
      count: "25+ Courses",
      icon: "fa-solid fa-paw",
      color: "#059669",
      bgColor: "#d1fae5",
      description: "B.V.Sc & A.H (Veterinary Doctor), B.F.Sc, Dairy Husbandry.",
      topExams: ["NEET-UG (VCI)", "State PVT"],
      courses: [
        { name: "B.V.Sc & A.H (Veterinary Doctor)", duration: "5.5 Years", eligibility: "10+2 PCB + NEET/PVT", avgFee: "₹30K - ₹2.5L/yr", scope: "Veterinary Surgeon, Livestock Officer" }
      ]
    },
    {
      id: "defence-paramilitary",
      name: "Defence & Paramilitary",
      count: "15+ Courses",
      icon: "fa-solid fa-shield-halved",
      color: "#1e293b",
      bgColor: "#f1f5f9",
      description: "NDA, CDS, AFCAT, Military Nursing (MNS), Fire & Industrial Safety.",
      topExams: ["UPSC NDA", "UPSC CDS", "AFCAT"],
      courses: [
        { name: "NDA Coaching & SSB Integrated", duration: "1 - 2 Years", eligibility: "10+2 PCM/Any (Unmarried)", avgFee: "₹40K - ₹1.5L", scope: "Commissioned Officer in Armed Forces" }
      ]
    }
  ],

  // =========================================================================
  // 4. TOP MEDICAL COLLEGES MASTER DATASET
  // =========================================================================
  colleges: [
    {
      id: "aiims-delhi",
      name: "All India Institute of Medical Sciences (AIIMS)",
      city: "New Delhi",
      state: "Delhi",
      type: "Government",
      nirfRank: 1,
      stateRank: 1,
      seats: 125,
      tuitionFee: 1628,
      hostelFee: 4200,
      totalAnnualFee: "₹5,828/yr",
      neetClosingRankUR: 57,
      neetClosingRankOBC: 236,
      neetClosingRankSC: 875,
      neetClosingRankST: 1650,
      counselling: "MCC (AIQ 100%)",
      counsellingUrl: "https://mcc.nic.in",
      officialWebsite: "https://www.aiims.edu",
      quota: "100% All India Quota (AIQ)",
      admissionProcess: "NEET UG score via Medical Counselling Committee (MCC) Online AIQ Rounds.",
      highlights: "Rank #1 Medical College in India. World-class research, highest clinical exposure, nominal government fee structure."
    },
    {
      id: "gmc-bhopal",
      name: "Gandhi Medical College (GMC Bhopal)",
      city: "Bhopal",
      state: "Madhya Pradesh",
      type: "Government",
      nirfRank: 38,
      stateRank: 1,
      seats: 250,
      tuitionFee: 100000,
      hostelFee: 14000,
      totalAnnualFee: "₹1,14,000/yr",
      neetClosingRankUR: 8400,
      neetClosingRankOBC: 12500,
      neetClosingRankSC: 52000,
      neetClosingRankST: 98000,
      counselling: "MP DME (85% State) + MCC (15% AIQ)",
      counsellingUrl: "https://dme.mponline.gov.in",
      officialWebsite: "https://gmcbhopal.net",
      quota: "85% MP State Domicile + 15% AIQ",
      admissionProcess: "MP DME Online Counselling through MPOnline portal with 100% MMVY fee waiver eligibility.",
      highlights: "Madhya Pradesh's premier government medical college affiliated to Hamidia & Sultania Hospitals (2,000+ beds)."
    },
    {
      id: "mgm-indore",
      name: "Mahatma Gandhi Memorial Medical College (MGM Indore)",
      city: "Indore",
      state: "Madhya Pradesh",
      type: "Government",
      nirfRank: 42,
      stateRank: 2,
      seats: 250,
      tuitionFee: 100000,
      hostelFee: 12000,
      totalAnnualFee: "₹1,12,000/yr",
      neetClosingRankUR: 6800,
      neetClosingRankOBC: 9900,
      neetClosingRankSC: 44000,
      neetClosingRankST: 86000,
      counselling: "MP DME (85% State) + MCC (15% AIQ)",
      counsellingUrl: "https://dme.mponline.gov.in",
      officialWebsite: "https://mgmmcindore.in",
      quota: "85% MP State Quota + 15% AIQ",
      admissionProcess: "MP DME State Counselling via MPOnline.",
      highlights: "Oldest medical college in MP (estd 1948) with MY Hospital. Highest cutoff in MP state counselling."
    },
    {
      id: "aiims-bhopal",
      name: "All India Institute of Medical Sciences (AIIMS Bhopal)",
      city: "Bhopal",
      state: "Madhya Pradesh",
      type: "Government",
      nirfRank: 24,
      stateRank: 1,
      seats: 125,
      tuitionFee: 5856,
      hostelFee: 4200,
      totalAnnualFee: "₹10,056/yr",
      neetClosingRankUR: 550,
      neetClosingRankOBC: 1200,
      neetClosingRankSC: 8500,
      neetClosingRankST: 19000,
      counselling: "MCC (100% AIQ)",
      counsellingUrl: "https://mcc.nic.in",
      officialWebsite: "https://aiimsbhopal.edu.in",
      quota: "100% AIQ Central Quota",
      admissionProcess: "MCC Online NEET UG Counselling.",
      highlights: "Apex Central Government Institute of National Importance with world-class tertiary trauma care."
    },
    {
      id: "peoples-bhopal",
      name: "People's College of Medical Sciences (PCMS)",
      city: "Bhopal",
      state: "Madhya Pradesh",
      type: "Private",
      nirfRank: 78,
      stateRank: 3,
      seats: 250,
      tuitionFee: 1265000,
      hostelFee: 120000,
      totalAnnualFee: "₹13,85,000/yr",
      neetClosingRankUR: 145000,
      neetClosingRankOBC: 162000,
      neetClosingRankSC: 340000,
      neetClosingRankST: 520000,
      counselling: "MP DME State Counselling",
      counsellingUrl: "https://dme.mponline.gov.in",
      officialWebsite: "https://peoplesuniversity.edu.in",
      quota: "85% MP State Domicile + NRI / Management Quota",
      admissionProcess: "MP DME Online Counselling rounds on MPOnline.",
      highlights: "1000+ bed NABH hospital in Bhopal with high OPD load and state-approved fee structure."
    },
    {
      id: "ln-medical-bhopal",
      name: "LN Medical College and JK Hospital",
      city: "Bhopal",
      state: "Madhya Pradesh",
      type: "Private",
      nirfRank: 85,
      stateRank: 4,
      seats: 250,
      tuitionFee: 1320000,
      hostelFee: 135000,
      totalAnnualFee: "₹14,55,000/yr",
      neetClosingRankUR: 138000,
      neetClosingRankOBC: 154000,
      neetClosingRankSC: 320000,
      neetClosingRankST: 490000,
      counselling: "MP DME State Counselling",
      counsellingUrl: "https://dme.mponline.gov.in",
      officialWebsite: "https://lnmc.lnct.ac.in",
      quota: "85% MP State + Management/NRI",
      admissionProcess: "MP DME Centralized Counselling on MPOnline portal.",
      highlights: "Attached JK Hospital (1,200 beds) in Kolar Road, Bhopal with extensive super-specialty wings."
    },
    {
      id: "kmc-manipal",
      name: "Kasturba Medical College (KMC Manipal)",
      city: "Manipal",
      state: "Karnataka",
      type: "Deemed",
      nirfRank: 9,
      stateRank: 1,
      seats: 250,
      tuitionFee: 1780000,
      hostelFee: 140000,
      totalAnnualFee: "₹19,20,000/yr",
      neetClosingRankUR: 42000,
      neetClosingRankOBC: 45000,
      neetClosingRankSC: 180000,
      neetClosingRankST: 290000,
      counselling: "MCC Deemed University Counselling",
      counsellingUrl: "https://mcc.nic.in",
      officialWebsite: "https://manipal.edu/kmc-manipal.html",
      quota: "100% All India Deemed Quota + NRI Quota",
      admissionProcess: "MCC Online Deemed Universities Portal rounds.",
      highlights: "Rank #9 NIRF overall in India. Global recognition with high USMLE/PLAB success rate and modern clinical simulation."
    },
    {
      id: "dy-patil-pune",
      name: "Dr. D. Y. Patil Medical College & Hospital",
      city: "Pune",
      state: "Maharashtra",
      type: "Deemed",
      nirfRank: 15,
      stateRank: 2,
      seats: 250,
      tuitionFee: 2600000,
      hostelFee: 280000,
      totalAnnualFee: "₹28,80,000/yr",
      neetClosingRankUR: 320000,
      neetClosingRankOBC: 345000,
      neetClosingRankSC: 550000,
      neetClosingRankST: 780000,
      counselling: "MCC Deemed Universities AIQ",
      counsellingUrl: "https://mcc.nic.in",
      officialWebsite: "https://medical.dpu.edu.in",
      quota: "85% Management Quota (All India) + 15% NRI Quota",
      admissionProcess: "MCC Online Deemed Counselling.",
      highlights: "Rank #15 NIRF. Asia's largest private hi-tech 2,000-bed hospital with 4th-generation da Vinci surgical robot."
    },
    {
      id: "kgmu-lucknow",
      name: "King George's Medical University (KGMU)",
      city: "Lucknow",
      state: "Uttar Pradesh",
      type: "Government",
      nirfRank: 12,
      stateRank: 2,
      seats: 250,
      tuitionFee: 54600,
      hostelFee: 18000,
      totalAnnualFee: "₹72,600/yr",
      neetClosingRankUR: 1800,
      neetClosingRankOBC: 2800,
      neetClosingRankSC: 18000,
      neetClosingRankST: 35000,
      counselling: "UP DGME (85% State) + MCC (15% AIQ)",
      counsellingUrl: "https://upneet.gov.in",
      officialWebsite: "https://www.kgmu.org",
      quota: "15% AIQ + 85% UP State Domicile Quota",
      admissionProcess: "NEET UG qualified via UP NEET state counselling or MCC AIQ.",
      highlights: "Over 115 years of legacy. Massive 4,500+ bed hospital complex offering high patient flow."
    }
  ],

  // =========================================================================
  // 5. SCHOLARSHIPS MASTER DATASET
  // =========================================================================
  scholarships: [
    {
      id: "mp-medhavi-vidhyarthi",
      name: "Mukhyamantri Medhavi Vidhyarthi Yojana (MMVY)",
      authority: "Govt. of Madhya Pradesh (Higher Education Dept)",
      type: "State",
      state: "Madhya Pradesh",
      targetCategory: ["General", "OBC", "SC", "ST", "EWS"],
      courseLevel: ["Medical", "Engineering", "Management", "Law"],
      amount: "100% Full Tuition Fee Paid by MP Govt (Even in Private Colleges)",
      incomeLimit: 600000,
      minMarks: 70,
      gender: "All",
      deadline: "Rolling / Academic Session Year",
      officialPortal: "http://scholarshipportal.mp.nic.in/MedhaviChhatra",
      portalName: "MP State Scholarship Portal 2.0",
      documents: ["MP Domicile Certificate", "Income Certificate (<6L)", "12th Marksheet", "NEET / JEE Allotment Letter", "Aadhaar Card"],
      description: "Flagship MP scholarship covering 100% tuition fees of MBBS (Govt & Private in MP), IIT, NIT, and NLU."
    },
    {
      id: "nsp-central-sector",
      name: "Central Sector Scheme of Scholarships for College & University Students",
      authority: "Ministry of Education (Govt. of India)",
      type: "Central",
      state: "All India",
      targetCategory: ["General", "OBC", "SC", "ST", "EWS"],
      courseLevel: ["Medical", "Engineering", "Management", "Science", "Law", "General"],
      amount: "₹12,000/yr (Graduation) to ₹20,000/yr (Post-Grad)",
      incomeLimit: 450000,
      minMarks: 80,
      gender: "All",
      deadline: "31st October (Annual)",
      officialPortal: "https://scholarships.gov.in",
      portalName: "National Scholarship Portal (NSP)",
      documents: ["12th Marksheet", "Income Certificate (<4.5L)", "Aadhaar Card", "College Fee Receipt", "DBT Bank Passbook"],
      description: "Direct Bank Transfer scheme for top 20th percentile 12th board students in regular UG/PG degree courses."
    },
    {
      id: "aicte-pragati-girls",
      name: "AICTE Pragati Scholarship Scheme for Girl Students",
      authority: "AICTE (Ministry of Education)",
      type: "Central",
      state: "All India",
      targetCategory: ["General", "OBC", "SC", "ST", "EWS"],
      courseLevel: ["Engineering", "Science"],
      amount: "₹50,000 per annum (Every year till course completion)",
      incomeLimit: 800000,
      minMarks: 50,
      gender: "Female",
      deadline: "31st December (Annual)",
      officialPortal: "https://scholarships.gov.in",
      portalName: "National Scholarship Portal (NSP)",
      documents: ["AICTE Approved Admission Slip", "Income Certificate (<8L)", "10th/12th Marksheet", "Aadhaar"],
      description: "Financial aid of ₹50,000/yr to up to 2 girls per family in AICTE approved institutions."
    }
  ],

  // =========================================================================
  // 6. COUNSELLING AUTHORITIES DIRECTORY
  // =========================================================================
  counsellingAuthorities: [
    {
      name: "Medical Counselling Committee (MCC)",
      level: "Central / All India",
      website: "https://mcc.nic.in",
      covers: "15% AIQ MBBS/BDS Seats, 100% Deemed Universities, Central Universities (AIIMS, JIPMER, BHU, AMU)",
      flow: "Registration → Choice Filling → Round 1 Allotment → Round 2 → Mop-up / Round 3 → Stray Vacancy",
      contact: "Email: admissions@mcc.nic.in"
    },
    {
      name: "Directorate of Medical Education MP (MP DME)",
      level: "State (Madhya Pradesh)",
      website: "https://dme.mponline.gov.in",
      covers: "85% State Quota Govt Medical Colleges + 100% MP Private Medical & Dental Colleges",
      flow: "MPOnline Profile Creation → Domicile & Category Verification → Merit List → Choice Filling → Seat Allotment",
      contact: "Helpline: 0755-6720200"
    },
    {
      name: "Directorate General of Medical Education UP (UP DGME)",
      level: "State (Uttar Pradesh)",
      website: "https://upneet.gov.in",
      covers: "85% UP Govt MBBS Seats + 100% UP Private Medical Colleges (Open State for all India candidates)",
      flow: "Online Registration + Security Deposit → Nodal Center Verification → Choice Filling → Allotment",
      contact: "Email: upneetcounselling2024@gmail.com"
    }
  ]
};

// Expose to window and node
if (typeof window !== 'undefined') {
  window.EDUCATION_DATA = EDUCATION_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = EDUCATION_DATA;
}
