/**
 * EDUCATION SATHI - MAHARASHTRA TOP 200 MEDICAL & HEALTH SCIENCE COLLEGES MASTER DATASET
 * Complete 1 to 200 Colleges (Government MBBS, Private & Deemed MBBS, BDS Dental,
 * BAMS Ayurveda, BHMS Homeopathy, BUMS Unani, B.Sc Nursing, BPT Physiotherapy, BASLP & Allied Medical).
 */
const MH_TOP_200_COLLEGES = [
  {
    "rank": 1,
    "name": "Grant Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-1",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 2,
    "name": "Seth GS Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-2",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 3,
    "name": "BJ Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-3",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 4,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-4",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 5,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-5",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 6,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Miraj",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-6",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 7,
    "name": "Dr. Vaishampayan Memorial Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Solapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-7",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 8,
    "name": "Indira Gandhi Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-8",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 9,
    "name": "Shri Vasantrao Naik Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Yavatmal",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-9",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 10,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Akola",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-10",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 11,
    "name": "SRTR Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Ambajogai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-11",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 12,
    "name": "Dr. Shankarrao Chavan Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Nanded",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-12",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 13,
    "name": "Shri Bhausaheb Hire Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Dhule",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-13",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 14,
    "name": "Rajashree Chhatrapati Shahu Maharaj Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-14",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 15,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Latur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-15",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 16,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Chandrapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-16",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 17,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Gondia",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-17",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 18,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Jalgaon",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-18",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 19,
    "name": "Government Medical College & Hospital",
    "course": "MBBS",
    "type": "Govt",
    "city": "Baramati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-19",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 20,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Nandurbar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-20",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 21,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Alibag",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-21",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 22,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Satara",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-22",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 23,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Sindhudurg",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-23",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 24,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Dharashiv",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-24",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 25,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Ratnagiri",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-25",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 26,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Parbhani",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-26",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 27,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-27",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 28,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Jalna",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-28",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 29,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Hingoli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-29",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 30,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Washim",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-30",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 31,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Buldhana",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-31",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 32,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-32",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 33,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Bhandara",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-33",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 34,
    "name": "Government Medical College",
    "course": "MBBS",
    "type": "Govt",
    "city": "Gadchiroli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Govt MBBS",
    "id": "mh-col-34",
    "state": "Maharashtra",
    "estFee": "₹1,25,000/yr (State Domicile & AIQ)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 35,
    "name": "Bharati Vidyapeeth Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-35",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 36,
    "name": "D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-36",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 37,
    "name": "Krishna Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Karad",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-37",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 38,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-38",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 39,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-39",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 40,
    "name": "Dr. D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-40",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 41,
    "name": "Symbiosis Medical College for Women",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-41",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 42,
    "name": "Datta Meghe Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-42",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 43,
    "name": "Jawaharlal Nehru Medical College, Datta Meghe",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-43",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 44,
    "name": "Mahatma Gandhi Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-44",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 45,
    "name": "Jawaharlal Nehru Medical College",
    "course": "MBBS",
    "type": "Private/Deemed",
    "city": "Sawangi, Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-45",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 46,
    "name": "Dr. Vithalrao Vikhe Patil Foundation Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Ahmednagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-46",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 47,
    "name": "Bharati Vidyapeeth Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Sangli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-47",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 48,
    "name": "Terna Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-48",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 49,
    "name": "K.J. Somaiya Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-49",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 50,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Private/Deemed",
    "city": "Aurangabad",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 Yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-50",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 51,
    "name": "ACPM Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Dhule",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-51",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 52,
    "name": "Ashwini Rural Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Solapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-52",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 53,
    "name": "B.K.L. Walawalkar Rural Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Ratnagiri",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-53",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 54,
    "name": "Bharatratna Atal Bihari Vajpayee Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-54",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 55,
    "name": "Dr. N.Y. Tasgaonkar Institute of Medical Science",
    "course": "MBBS",
    "type": "Private",
    "city": "Karjat/Raigad",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-55",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 56,
    "name": "Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-56",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 57,
    "name": "Dr. Rajendra Gode Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-57",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 58,
    "name": "Dr. Ulhas Patil Medical College & Hospital",
    "course": "MBBS",
    "type": "Private",
    "city": "Jalgaon",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-58",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 59,
    "name": "Dr. Vithalrao Vikhe Patil Foundation Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Ahmednagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-59",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 60,
    "name": "Dr. Vasantrao Pawar Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-60",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 61,
    "name": "Indian Institute of Medical Science & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Jalna",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-61",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 62,
    "name": "Jawaharlal Nehru Medical College, Sawangi",
    "course": "MBBS",
    "type": "Private/Deemed",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-62",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 63,
    "name": "K.J. Somaiya Medical College & Research Centre",
    "course": "MBBS",
    "type": "Private",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-63",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 64,
    "name": "Maharashtra Institute of Medical Sciences & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Latur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-64",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 65,
    "name": "Maharashtra Institute of Medical Education & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Talegaon, Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-65",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 66,
    "name": "Mahatma Gandhi Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Sevagram, Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-66",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 67,
    "name": "Mahatma Gandhi Missions Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-67",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 68,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-68",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 69,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Vashi, Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-69",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 70,
    "name": "N.K.P. Salve Institute of Medical Sciences & Research Centre",
    "course": "MBBS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-70",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 71,
    "name": "Padmashree Dr. D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-71",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 72,
    "name": "Parbhani Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Parbhani",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-72",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 73,
    "name": "Pravara Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Loni",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-73",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 74,
    "name": "Rajarshi Chhatrapati Shahu Maharaj Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-74",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 75,
    "name": "Smt. Kashibai Navale Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-75",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 76,
    "name": "Terna Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-76",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 77,
    "name": "Vedantaa Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Palghar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-77",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 78,
    "name": "Vinayaka Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-78",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 79,
    "name": "D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-79",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 80,
    "name": "D.Y. Patil Medical College, Hospital & Research Centre",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pimpri, Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-80",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 81,
    "name": "Bharati Vidyapeeth Deemed University Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-81",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 82,
    "name": "Bharati Vidyapeeth Deemed University Medical College & Hospital",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Sangli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-82",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 83,
    "name": "Datta Meghe Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-83",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 84,
    "name": "Jawaharlal Nehru Medical College, Datta Meghe Institute",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-84",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 85,
    "name": "Krishna Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Karad",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-85",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 86,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-86",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 87,
    "name": "MGM Medical College & Hospital",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-87",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 88,
    "name": "Padmashree Dr. D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-88",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 89,
    "name": "Dr. D.Y. Patil Medical College, Hospital & Research Centre",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pimpri, Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-89",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 90,
    "name": "Pravara Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Loni",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-90",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 91,
    "name": "Symbiosis Medical College for Women",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-91",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 92,
    "name": "Datta Meghe Institute of Higher Education & Research",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-92",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 93,
    "name": "Mahatma Gandhi Missions Medical College",
    "course": "MBBS",
    "type": "Private/Deemed",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-93",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 94,
    "name": "Mahatma Gandhi Missions Medical College",
    "course": "MBBS",
    "type": "Private/Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-94",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 95,
    "name": "KJ Somaiya Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-95",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 96,
    "name": "Terna Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-96",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 97,
    "name": "Smt. Kashibai Navale Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-97",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 98,
    "name": "Maharashtra Institute of Medical Education & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Talegaon, Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-98",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 99,
    "name": "Dr. Vasantrao Pawar Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-99",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 100,
    "name": "Vedantaa Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Palghar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-100",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 101,
    "name": "B.K.L. Walawalkar Rural Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Ratnagiri",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-101",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 102,
    "name": "Ashwini Rural Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Solapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-102",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 103,
    "name": "Dr. Rajendra Gode Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-103",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 104,
    "name": "Dr. Panjabrao Deshmukh Memorial Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-104",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 105,
    "name": "Dr. Ulhas Patil Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Jalgaon",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-105",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 106,
    "name": "Indian Institute of Medical Science & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Jalna",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-106",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 107,
    "name": "Maharashtra Institute of Medical Sciences & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Latur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-107",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 108,
    "name": "N.K.P. Salve Institute of Medical Sciences",
    "course": "MBBS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-108",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 109,
    "name": "Dr. Vithalrao Vikhe Patil Foundation Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Ahmednagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-109",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 110,
    "name": "Bharatratna Atal Bihari Vajpayee Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-110",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 111,
    "name": "ACPM Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Dhule",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-111",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 112,
    "name": "JIIU's Indian Institute of Medical Science & Research",
    "course": "MBBS",
    "type": "Private",
    "city": "Jalna",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-112",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 113,
    "name": "Rajarshi Chhatrapati Shahu Maharaj Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-113",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 114,
    "name": "KIMS Medical College",
    "course": "MBBS",
    "type": "Private",
    "city": "Karad",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-114",
    "state": "Maharashtra",
    "estFee": "₹8,50,000 - ₹14,50,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell (85% State + 15% NRI/Mgmt)"
  },
  {
    "rank": 115,
    "name": "Jawaharlal Nehru Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-115",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 116,
    "name": "MGM Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Aurangabad/Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-116",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 117,
    "name": "D.Y. Patil Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-117",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 118,
    "name": "Bharati Vidyapeeth Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-118",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 119,
    "name": "Bharati Vidyapeeth Medical College",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Sangli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-119",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 120,
    "name": "Symbiosis Medical College for Women",
    "course": "MBBS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "Private/Deemed MBBS",
    "id": "mh-col-120",
    "state": "Maharashtra",
    "estFee": "₹18,00,000 - ₹26,00,000/yr",
    "counsellingBody": "MCC Deemed University AIQ Counselling"
  },
  {
    "rank": 121,
    "name": "Government Dental College & Hospital",
    "course": "BDS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-121",
    "state": "Maharashtra",
    "estFee": "₹60,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 122,
    "name": "Government Dental College & Hospital",
    "course": "BDS",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-122",
    "state": "Maharashtra",
    "estFee": "₹60,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 123,
    "name": "Government Dental College & Hospital",
    "course": "BDS",
    "type": "Govt",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-123",
    "state": "Maharashtra",
    "estFee": "₹60,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 124,
    "name": "Nair Hospital Dental College",
    "course": "BDS",
    "type": "Govt/Corporation",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-124",
    "state": "Maharashtra",
    "estFee": "₹60,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 125,
    "name": "Bharati Vidyapeeth Dental College & Hospital",
    "course": "BDS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-125",
    "state": "Maharashtra",
    "estFee": "₹4,50,000 - ₹6,50,000/yr",
    "counsellingBody": "MCC Deemed University BDS AIQ"
  },
  {
    "rank": 126,
    "name": "Bharati Vidyapeeth Dental College & Hospital",
    "course": "BDS",
    "type": "Deemed",
    "city": "Sangli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-126",
    "state": "Maharashtra",
    "estFee": "₹4,50,000 - ₹6,50,000/yr",
    "counsellingBody": "MCC Deemed University BDS AIQ"
  },
  {
    "rank": 127,
    "name": "D.Y. Patil Dental School",
    "course": "BDS",
    "type": "Deemed/Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-127",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 128,
    "name": "Dr. D.Y. Patil Dental College & Hospital",
    "course": "BDS",
    "type": "Deemed",
    "city": "Pimpri, Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-128",
    "state": "Maharashtra",
    "estFee": "₹4,50,000 - ₹6,50,000/yr",
    "counsellingBody": "MCC Deemed University BDS AIQ"
  },
  {
    "rank": 129,
    "name": "MGM Dental College & Hospital",
    "course": "BDS",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-129",
    "state": "Maharashtra",
    "estFee": "₹4,50,000 - ₹6,50,000/yr",
    "counsellingBody": "MCC Deemed University BDS AIQ"
  },
  {
    "rank": 130,
    "name": "MGM Dental College & Hospital",
    "course": "BDS",
    "type": "Deemed",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-130",
    "state": "Maharashtra",
    "estFee": "₹4,50,000 - ₹6,50,000/yr",
    "counsellingBody": "MCC Deemed University BDS AIQ"
  },
  {
    "rank": 131,
    "name": "Sinhgad Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-131",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 132,
    "name": "M.A. Rangoonwala College of Dental Sciences",
    "course": "BDS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-132",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 133,
    "name": "Tatyasaheb Kore Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-133",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 134,
    "name": "Y.M.T. Dental College & Research Institute",
    "course": "BDS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-134",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 135,
    "name": "Terna Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-135",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 136,
    "name": "Bharati Vidyapeeth Dental College",
    "course": "BDS",
    "type": "Private/Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-136",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 137,
    "name": "CSMSS Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-137",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 138,
    "name": "Rural Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Loni",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-138",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 139,
    "name": "Sharad Pawar Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-139",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 140,
    "name": "VSPM Dental College & Research Centre",
    "course": "BDS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-140",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 141,
    "name": "Swargiya Dadasaheb Kalmegh Smruti Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-141",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 142,
    "name": "Government Dental College",
    "course": "BDS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-142",
    "state": "Maharashtra",
    "estFee": "₹60,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 143,
    "name": "MIDSR Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Latur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-143",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 144,
    "name": "ACPM Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Dhule",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-144",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 145,
    "name": "SMBT Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-145",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 146,
    "name": "Karmaveer Bhaurao Patil Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Satara",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-146",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 147,
    "name": "Aditya Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Beed",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-147",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 148,
    "name": "Yogita Dental College & Hospital",
    "course": "BDS",
    "type": "Private",
    "city": "Khed, Ratnagiri",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-148",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 149,
    "name": "Mahatma Gandhi Vidyamandir Dental College",
    "course": "BDS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-149",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 150,
    "name": "Nanded Rural Dental College & Research Centre",
    "course": "BDS",
    "type": "Private",
    "city": "Nanded",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5 yr",
    "category": "BDS Dental",
    "id": "mh-col-150",
    "state": "Maharashtra",
    "estFee": "₹3,20,000 - ₹4,80,000/yr (FRA Approved)",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 151,
    "name": "Government Ayurved College & Hospital",
    "course": "BAMS",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-151",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 152,
    "name": "Government Ayurved College",
    "course": "BAMS",
    "type": "Govt",
    "city": "Nanded",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-152",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 153,
    "name": "Government Ayurved College",
    "course": "BAMS",
    "type": "Govt",
    "city": "Osmanabad/Dharashiv",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-153",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 154,
    "name": "R.A. Podar Ayurved Medical College",
    "course": "BAMS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-154",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 155,
    "name": "Shree Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-155",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 156,
    "name": "Shri Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-156",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 157,
    "name": "Bharati Vidyapeeth Deemed University College of Ayurved",
    "course": "BAMS",
    "type": "Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-157",
    "state": "Maharashtra",
    "estFee": "₹2,50,000 - ₹4,50,000/yr",
    "counsellingBody": "Deemed University / AACCC"
  },
  {
    "rank": 158,
    "name": "Dr. D.Y. Patil College of Ayurved",
    "course": "BAMS",
    "type": "Deemed/Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-158",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 159,
    "name": "Tilak Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-159",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 160,
    "name": "Ashtang Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-160",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 161,
    "name": "Smt. K.G. Mittal Ayurvedic College",
    "course": "BAMS",
    "type": "Private",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-161",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 162,
    "name": "Ayurved Mahavidyalaya & Hospital",
    "course": "BAMS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-162",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 163,
    "name": "Matoshri Ayurved College",
    "course": "BAMS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-163",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 164,
    "name": "Shri Gurudev Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Amravati",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-164",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 165,
    "name": "Dhanwantari Ayurved Medical College",
    "course": "BAMS",
    "type": "Private",
    "city": "Udgir",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-165",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 166,
    "name": "Shree Saptashrungi Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-166",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 167,
    "name": "Yashwant Ayurvedic College",
    "course": "BAMS",
    "type": "Private",
    "city": "Kodoli, Kolhapur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-167",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 168,
    "name": "Bharati Ayurved Hospital & Medical College",
    "course": "BAMS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-168",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 169,
    "name": "S.D.M. Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-169",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 170,
    "name": "K.D.M.G. Ayurved College",
    "course": "BAMS",
    "type": "Private",
    "city": "Chikhli",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-170",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 171,
    "name": "Shri Ayurved Mahavidyalaya & Hospital",
    "course": "BAMS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-171",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 172,
    "name": "Datta Meghe Ayurvedic Medical College",
    "course": "BAMS",
    "type": "Private/Deemed",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-172",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 173,
    "name": "Shree Ayurved College & Hospital",
    "course": "BAMS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-173",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 174,
    "name": "Pravara Ayurved Mahavidyalaya",
    "course": "BAMS",
    "type": "Private/Deemed",
    "city": "Loni",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-174",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 175,
    "name": "Mahatma Gandhi Ayurved College",
    "course": "BAMS",
    "type": "Deemed",
    "city": "Wardha",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BAMS Ayurveda",
    "id": "mh-col-175",
    "state": "Maharashtra",
    "estFee": "₹2,50,000 - ₹4,50,000/yr",
    "counsellingBody": "Deemed University / AACCC"
  },
  {
    "rank": 176,
    "name": "Government Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-176",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 177,
    "name": "Government Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-177",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 178,
    "name": "Bharati Vidyapeeth Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Deemed/Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-178",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 179,
    "name": "Smt. Chandaben Mohanbhai Patel Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Private",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-179",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 180,
    "name": "Maharashtra Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Private",
    "city": "Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-180",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 181,
    "name": "DKMM Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Private",
    "city": "Chhatrapati Sambhajinagar",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-181",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 182,
    "name": "Smt. Kanchanbai B. Bhoyar Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Private",
    "city": "Nagpur",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-182",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 183,
    "name": "Chandrashekhar Deshmukh Homoeopathic Medical College",
    "course": "BHMS",
    "type": "Private",
    "city": "Pune",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BHMS Homeopathy",
    "id": "mh-col-183",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 184,
    "name": "Government Unani Medical College",
    "course": "BUMS",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-184",
    "state": "Maharashtra",
    "estFee": "₹45,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 185,
    "name": "Ayurvedic & Unani Tibbia College",
    "course": "BUMS",
    "type": "Govt/Aided",
    "city": "Mumbai/MH",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-185",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 186,
    "name": "Jamia Hamdard/Unani Medical College",
    "course": "BUMS",
    "type": "Private/Deemed",
    "city": "Maharashtra",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-186",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 187,
    "name": "Al-Badar Unani Medical College",
    "course": "BUMS",
    "type": "Private",
    "city": "Maharashtra",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-187",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 188,
    "name": "Anjuman-I-Islam Unani Medical College",
    "course": "BUMS",
    "type": "Private",
    "city": "Maharashtra",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-188",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 189,
    "name": "Mohammadia Tibbia College",
    "course": "BUMS",
    "type": "Private",
    "city": "Malegaon, Nashik",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-189",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 190,
    "name": "Unani Medical College & Hospital",
    "course": "BUMS",
    "type": "Private",
    "city": "Maharashtra",
    "eligibility": "12th PCB + NEET",
    "entrance": "NEET UG",
    "duration": "5.5 yr",
    "category": "BUMS Unani",
    "id": "mh-col-190",
    "state": "Maharashtra",
    "estFee": "₹1,80,000 - ₹2,80,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 191,
    "name": "College of Nursing, Sir J.J. Hospital",
    "course": "B.Sc Nursing",
    "type": "Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB + English",
    "entrance": "MH B.Sc Nursing CET / NEET",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-191",
    "state": "Maharashtra",
    "estFee": "₹18,000 - ₹30,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 192,
    "name": "College of Nursing, Government Medical College",
    "course": "B.Sc Nursing",
    "type": "Govt",
    "city": "Nagpur",
    "eligibility": "12th PCB + English",
    "entrance": "MH B.Sc Nursing CET",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-192",
    "state": "Maharashtra",
    "estFee": "₹18,000 - ₹30,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 193,
    "name": "College of Nursing, BJ Government Medical College",
    "course": "B.Sc Nursing",
    "type": "Govt",
    "city": "Pune",
    "eligibility": "12th PCB + English",
    "entrance": "MH B.Sc Nursing CET",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-193",
    "state": "Maharashtra",
    "estFee": "₹18,000 - ₹30,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 194,
    "name": "Bharati Vidyapeeth College of Nursing",
    "course": "B.Sc Nursing",
    "type": "Private/Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + English",
    "entrance": "University Entrance / State CET",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-194",
    "state": "Maharashtra",
    "estFee": "₹80,000 - ₹1,40,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 195,
    "name": "Dr. D.Y. Patil College of Nursing",
    "course": "B.Sc Nursing",
    "type": "Private/Deemed",
    "city": "Pune",
    "eligibility": "12th PCB + English",
    "entrance": "University Process",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-195",
    "state": "Maharashtra",
    "estFee": "₹80,000 - ₹1,40,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 196,
    "name": "MGM Institute of Health Sciences – College of Nursing",
    "course": "B.Sc Nursing",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th PCB + English",
    "entrance": "University Process",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-196",
    "state": "Maharashtra",
    "estFee": "₹2,50,000 - ₹4,50,000/yr",
    "counsellingBody": "Deemed University / AACCC"
  },
  {
    "rank": 197,
    "name": "Bharati Vidyapeeth College of Physiotherapy",
    "course": "BPT",
    "type": "Deemed/Private",
    "city": "Pune",
    "eligibility": "12th PCB",
    "entrance": "NEET / University CET",
    "duration": "4.5 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-197",
    "state": "Maharashtra",
    "estFee": "₹80,000 - ₹1,40,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 198,
    "name": "Dr. D.Y. Patil College of Physiotherapy",
    "course": "BPT",
    "type": "Deemed/Private",
    "city": "Pune",
    "eligibility": "12th PCB",
    "entrance": "NEET / University CET",
    "duration": "4.5 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-198",
    "state": "Maharashtra",
    "estFee": "₹80,000 - ₹1,40,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 199,
    "name": "Ali Yavar Jung National Institute of Speech & Hearing Disabilities",
    "course": "BASLP / Allied",
    "type": "Central Govt",
    "city": "Mumbai",
    "eligibility": "12th PCB/PCM as applicable",
    "entrance": "AYJNISHD Entrance",
    "duration": "4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-199",
    "state": "Maharashtra",
    "estFee": "₹25,000/yr",
    "counsellingBody": "Maharashtra State CET Cell / DMER"
  },
  {
    "rank": 200,
    "name": "MGM Institute of Health Sciences – Allied Health Sciences",
    "course": "Allied Medical",
    "type": "Deemed",
    "city": "Navi Mumbai",
    "eligibility": "12th with required science subjects",
    "entrance": "University Process",
    "duration": "3-4 yr",
    "category": "Nursing & Allied",
    "id": "mh-col-200",
    "state": "Maharashtra",
    "estFee": "₹2,50,000 - ₹4,50,000/yr",
    "counsellingBody": "Deemed University / AACCC"
  }
];
